### PR TITLE
Add `trt_hardware_compatibility_level` option for TensorRT engine export

### PR DESCRIPTION
**Pull request by onuralpszr**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://www.ultralytics.com/actions)</sub>

### 🌟 Summary

Added the `hw_compat` option to TensorRT export so engines can target compatible NVIDIA GPU families instead of only the export GPU.

### 📊 Key Changes

- Added `hw_compat` with supported values `ampere_plus` and `same_compute_capability`, defaulting to `None`.
- Passed the option through `export_engine()` to `onnx2engine()`, where it sets TensorRT’s hardware compatibility level.
- Added validation for unsupported values and TensorRT versions that do not expose the requested compatibility level.
- Required TensorRT `10.13.3.9` for hardware-compatible exports between Jetson Thor and DGX Spark ARM64 systems, while skipping the automatic TensorRT `10.15` installation in that workflow.
- Documented the option in TensorRT integration, export arguments, and the export format table.

### 🎯 Purpose & Impact

- TensorRT engines can be configured for compatible GPU families using `hw_compat`; leaving it unset retains export-GPU-only behavior.
- Cross-architecture engine portability remains unsupported between x86_64 and ARM64, and Blackwell inference remains limited to the x86_64 runtime.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @onuralpszr, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! This is an automated response to help streamline review. An Ultralytics engineer will follow up with you shortly for a detailed review. In the meantime, please review the checklist below to ensure a smooth merge:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). Ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: Update the relevant [documentation](https://docs.ultralytics.com/) for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your bug fix or feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_ — Bruce Lee

Additional notes for this PR:
- 🎯 Thanks for adding the new `trt_hardware_compatibility_level` option and wiring it through `default.yaml` and the export pipeline. Please double-check that CLI and Python usage are covered in docs and that docs build passes.
- 🧪 If feasible, consider a small exporter unit/integration test to validate accepted values (`ampere_plus`, `same_compute_capability`, `none`) and logging/validation behavior.
- 🧰 Confirm backwards compatibility: default behavior should remain unchanged when the arg is not provided.

For more guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing/). Don’t hesitate to leave a comment if you have any questions. Thank you for contributing to Ultralytics! 🚀

**Comment by onuralpszr** [comment]
@lakshanthad  please test on jetson devices as well. I saw support on old the way back to TRT 8 but if needed we can add  jetson condition to control properly based on your test.

**Review by lakshanthad — COMMENTED** [review]
Hi @onuralpszr.

Good stuff here!

I have tested this on Jetsons and here are my results:

You need to have TensorRT 10+ installed in order for `HardwareCompatibilityLevel` to work because for example, when I run on TensorRT 8, it complains about missing attribute:

```sh
TensorRT: starting export with TensorRT 8.5.2.2...
[09/27/2025-23:36:13] [TRT] [I] [MemUsageChange] Init CUDA: CPU +215, GPU +0, now: CPU 1863, GPU 16948 (MiB)
[09/27/2025-23:36:15] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +302, GPU +431, now: CPU 2188, GPU 17401 (MiB)
ERROR ❌ TensorRT: export failure 6.6s: module 'tensorrt' has no attribute 'HardwareCompatibilityLevel'
Traceback (most recent call last):
  File "/home/nvidia/YOLO11/env/bin/yolo", line 10, in <module>
    sys.exit(entrypoint())
  File "/home/nvidia/YOLO11/ultralytics/ultralytics/cfg/__init__.py", line 990, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/nvidia/YOLO11/ultralytics/ultralytics/engine/model.py", line 736, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/home/nvidia/YOLO11/ultralytics/ultralytics/engine/exporter.py", line 516, in __call__
    f[1] = self.export_engine(dla=dla)
  File "/home/nvidia/YOLO11/ultralytics/ultralytics/engine/exporter.py", line 233, in outer_func
    raise e
  File "/home/nvidia/YOLO11/ultralytics/ultralytics/engine/exporter.py", line 225, in outer_func
    f = inner_func(*args, **kwargs)  # exported file/dir or tuple of (file/dir, *)
  File "/home/nvidia/YOLO11/ultralytics/ultralytics/engine/exporter.py", line 969, in export_engine
    onnx2engine(
  File "/home/nvidia/YOLO11/ultralytics/ultralytics/utils/export/__init__.py", line 117, in onnx2engine
    config.hardware_compatibility_level = trt.HardwareCompatibilityLevel.NONE
AttributeError: module 'tensorrt' has no attribute 'HardwareCompatibilityLevel
```

So this means original Jetson Nano, Jetson TX2 , Jetson Xavier NX and Jetson AGX Xavier are all out of the picture because you can only install JetPack4 and JetPack5 on them and these systems come with TensorRT 8. So our only option here is to go with the Jetson Orin series (Orin Nano, Orin NX, AGX Orin) which support JetPack6 with TensorRT 10 and maybe Jetson Thor in the near future :)

I think we also need to do some testing for the performance drops mentioned in TensorRT Python API when it comes to using `HardwareCompatibilityLevel`.

Screenshot 2025-09-28 at 12 05 32 AM

From my testing on Orins, `ampere_plus` gave some errors eventhough log says in the middle (TensorRT: setting hardware compatibility level to AMPERE_PLUS). However, a model got exported without issues.

```sh
(env) nvidia@ubuntu:~/YOLO11/ultralytics$ yolo export model=yolo11n.pt format=engine trt_hardware_compatibility_level=ampere_plus
WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics 8.3.203 🚀 Python-3.10.12 torch-2.5.0a0+872d972e41.nv24.08 CUDA:0 (Orin, 62841MiB)
YOLO11n summary (fused): 100 layers, 2,616,248 parameters, 0 gradients, 6.5 GFLOPs

PyTorch: starting from 'yolo11n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (5.4 MB)

ONNX: starting export with onnx 1.17.0 opset 17...
ONNX: slimming with onnxslim 0.1.68...
ONNX: export success ✅ 2.0s, saved as 'yolo11n.onnx' (10.2 MB)

TensorRT: starting export with TensorRT 10.3.0...
[09/27/2025-23:37:41] [TRT] [I] [MemUsageChange] Init CUDA: CPU +2, GPU +0, now: CPU 623, GPU 12090 (MiB)
[09/27/2025-23:37:42] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +927, GPU +1096, now: CPU 1593, GPU 13227 (MiB)
[09/27/2025-23:37:42] [TRT] [E] IBuilderConfig::setHardwareCompatibilityLevel: Error Code 3: API Usage Error (Parameter check failed, condition: hardwareCompatibilityLevel == HardwareCompatibilityLevel::kNONE. Hardware compatibility level is not supported in current platform.)
TensorRT: setting hardware compatibility level to AMPERE_PLUS
[09/27/2025-23:37:42] [TRT] [I] ----------------------------------------------------------------
[09/27/2025-23:37:42] [TRT] [I] Input filename:   yolo11n.onnx
[09/27/2025-23:37:42] [TRT] [I] ONNX IR version:  0.0.8
[09/27/2025-23:37:42] [TRT] [I] Opset version:    17
[09/27/2025-23:37:42] [TRT] [I] Producer name:    pytorch
[09/27/2025-23:37:42] [TRT] [I] Producer version: 2.5.0
[09/27/2025-23:37:42] [TRT] [I] Domain:           
[09/27/2025-23:37:42] [TRT] [I] Model version:    0
[09/27/2025-23:37:42] [TRT] [I] Doc string:
```

whereas  `same_compute_capability` gave the below error:

```sh
TensorRT: starting export with TensorRT 10.3.0...
[09/27/2025-23:45:45] [TRT] [I] [MemUsageChange] Init CUDA: CPU +2, GPU +0, now: CPU 623, GPU 12094 (MiB)
[09/27/2025-23:45:47] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +927, GPU +1096, now: CPU 1593, GPU 13230 (MiB)
ERROR ❌ TensorRT: export failure 3.7s: type object 'tensorrt.tensorrt.HardwareCompatibilityLevel' has no attribute 'SAME_COMPUTE_CAPABILITY'
Traceback (most recent call last):
  File "/home/nvidia/YOLO11/env/bin/yolo", line 10, in <module>
    sys.exit(entrypoint())
  File "/home/nvidia/YOLO11/ultralytics/ultralytics/cfg/__init__.py", line 990, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/nvidia/YOLO11/ultralytics/ultralytics/engine/model.py", line 736, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/home/nvidia/YOLO11/ultralytics/ultralytics/engine/exporter.py", line 516, in __call__
    f[1] = self.export_engine(dla=dla)
  File "/home/nvidia/YOLO11/ultralytics/ultralytics/engine/exporter.py", line 233, in outer_func
    raise e
  File "/home/nvidia/YOLO11/ultralytics/ultralytics/engine/exporter.py", line 225, in outer_func
    f = inner_func(*args, **kwargs)  # exported file/dir or tuple of (file/dir, *)
  File "/home/nvidia/YOLO11/ultralytics/ultralytics/engine/exporter.py", line 969, in export_engine
    onnx2engine(
  File "/home/nvidia/YOLO11/ultralytics/ultralytics/utils/export/__init__.py", line 114, in onnx2engine
    config.hardware_compatibility_level = trt.HardwareCompatibilityLevel.SAME_COMPUTE_CAPABILITY
AttributeError: type object 'tensorrt.tensorrt.HardwareCompatibilityLevel' has no attribute 'SAME_COMPUTE_CAPABILITY'
```

**Comment by lakshanthad** [comment]
@onuralpszr Now that I have Jetson Thor, I went ahead and tested by exporting a `yolo11n` model to `tensorrt`  with AGX Orin (using `trt_hardware_compatibility_level=ampere_plus`) and inferencing using Jetson Thor. However, now the issue seem to be that both the devices need to be on the same TensorRT version.

Below is output for export using AGX Orin:

```sh
env) nvidia@ubuntu:~/YOLO11/ultralytics$ yolo export model=yolo11n.pt format=engine trt_hardware_compatibility_level=ampere_plus
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt': 37% ━━━━──────── 2.0/
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt': 100% ━━━━━━━━━━━━ 5.4
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt': 100% ━━━━━━━━━━━━ 5.4MB 40.5MB/s 0.1s
WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics 8.3.248 🚀 Python-3.10.12 torch-2.5.0a0+872d972e41.nv24.08 CUDA:0 (Orin, 62841MiB)
YOLO11n summary (fused): 100 layers, 2,616,248 parameters, 0 gradients, 6.5 GFLOPs

PyTorch: starting from 'yolo11n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (5.4 MB)

ONNX: starting export with onnx 1.20.0 opset 17...
ONNX: slimming with onnxslim 0.1.80...
ONNX: export success ✅ 1.6s, saved as 'yolo11n.onnx' (10.2 MB)

TensorRT: starting export with TensorRT 10.3.0...
[01/06/2026-17:03:25] [TRT] [I] [MemUsageChange] Init CUDA: CPU +2, GPU +0, now: CPU 640, GPU 7611 (MiB)
[01/06/2026-17:03:26] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +927, GPU +751, now: CPU 1610, GPU 8407 (MiB)
[01/06/2026-17:03:26] [TRT] [E] IBuilderConfig::setHardwareCompatibilityLevel: Error Code 3: API Usage Error (Parameter check failed, condition: hardwareCompatibilityLevel == HardwareCompatibilityLevel::kNONE. Hardware compatibility level is not supported in current platform.)
TensorRT: setting hardware compatibility level to AMPERE_PLUS
[01/06/2026-17:03:26] [TRT] [I] ----------------------------------------------------------------
[01/06/2026-17:03:26] [TRT] [I] Input filename:   yolo11n.onnx
[01/06/2026-17:03:26] [TRT] [I] ONNX IR version:  0.0.8
[01/06/2026-17:03:26] [TRT] [I] Opset version:    17
[01/06/2026-17:03:26] [TRT] [I] Producer name:    pytorch
[01/06/2026-17:03:26] [TRT] [I] Producer version: 2.5.0
[01/06/2026-17:03:26] [TRT] [I] Domain:           
[01/06/2026-17:03:26] [TRT] [I] Model version:    0
[01/06/2026-17:03:26] [TRT] [I] Doc string:       
[01/06/2026-17:03:26] [TRT] [I] ----------------------------------------------------------------
TensorRT: input "images" with shape(1, 3, 640, 640) DataType.FLOAT
TensorRT: output "output0" with shape(1, 84, 8400) DataType.FLOAT
TensorRT: building FP32 engine as yolo11n.engine
[01/06/2026-17:03:26] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[01/06/2026-17:05:15] [TRT] [I] Detected 1 inputs and 1 output network tensors.
[01/06/2026-17:05:16] [TRT] [I] Total Host Persistent Memory: 559312
[01/06/2026-17:05:16] [TRT] [I] Total Device Persistent Memory: 0
[01/06/2026-17:05:16] [TRT] [I] Total Scratch Memory: 2764800
[01/06/2026-17:05:16] [TRT] [I] [BlockAssignment] Started assigning block shifts. This will take 236 steps to complete.
[01/06/2026-17:05:16] [TRT] [I] [BlockAssignment] Algorithm ShiftNTopDown took 21.583ms to assign 11 blocks to 236 nodes requiring 19252224 bytes.
[01/06/2026-17:05:16] [TRT] [I] Total Activation Memory: 19251200
[01/06/2026-17:05:16] [TRT] [I] Total Weights Memory: 10588100
[01/06/2026-17:05:16] [TRT] [I] Engine generation completed in 110.126 seconds.
[01/06/2026-17:05:16] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 1 MiB, GPU 260 MiB
[01/06/2026-17:05:16] [TRT] [I] [MemUsageStats] Peak memory usage during Engine building and serialization: CPU: 2509 MiB
TensorRT: export success ✅ 113.7s, saved as 'yolo11n.engine' (11.8 MB)
```

Below is output for inference using Jetson Thor:

```sh
(env) thor@thor:~/YOLO11/ultralytics$ yolo detect predict model=yolo11n.engine
WARNING ⚠️ 'source' argument is missing. Using default 'source=/home/thor/YOLO11/ultralytics/ultralytics/assets'.
Ultralytics 8.3.248 🚀 Python-3.12.3 torch-2.9.1+cu130 CUDA:0 (NVIDIA Thor, 125772MiB)
Loading yolo11n.engine for TensorRT inference...
[01/06/2026-17:11:10] [TRT] [I] Loaded engine size: 11 MiB
[01/06/2026-17:11:10] [TRT] [E] IRuntime::deserializeCudaEngine: Error Code 1: Internal Error (Failed due to an old deserialization call on a newer plan file. This might happen when the plan file was built from an older TensorRT version. You can use `trtexec --getPlanVersionOnly` to check the version of TensorRT that was used to create the plan file. In deserializeEngine at runtime/api/engine.cpp:1454)
ERROR ❌ TensorRT model exported with a different version than 10.13.3.9

Traceback (most recent call last):
  File "/home/thor/YOLO11/env/bin/yolo", line 10, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/home/thor/YOLO11/ultralytics/ultralytics/cfg/__init__.py", line 985, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thor/YOLO11/ultralytics/ultralytics/engine/model.py", line 528, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/home/thor/YOLO11/ultralytics/ultralytics/engine/predictor.py", line 390, in setup_model
    self.model = AutoBackend(
                 ^^^^^^^^^^^^
  File "/home/thor/YOLO11/env/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/thor/YOLO11/ultralytics/ultralytics/nn/autobackend.py", line 373, in __init__
    raise e
  File "/home/thor/YOLO11/ultralytics/ultralytics/nn/autobackend.py", line 370, in __init__
    context = model.create_execution_context()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
```

Also it is hard to downgrade the TensorRT version of Jetson Thor to match with AGX Orin because of higher CUDA version requiring higher TensorRT version.

Have any ideas?

**Comment by lakshanthad** [comment]
@onuralpszr Here is my full report based on my testing on AGX Thor, DGX Spark and RTX Pro 6000:

On Jetson Thor and DGX Spark, `trt_hardware_compatibility_level` only works with `tensorrt 10.13.3.9`. Given that both devices are on this version of tensorrt, they work interchangeably. That is export on one and inference on the other. This works with both trtexec tool and Python API usage.

However, while exporting to engine files, there is this message:
```
TensorRT: building FP32 engine as yolo26n.engine
[03/05/2026-01:43:54] [TRT] [I] Lowering maximum device shared memory from 102400 to 49152 because of enabling hardware forward compatibility
[03/05/2026-01:43:54] [TRT] [I] Lowering maximum device shared memory from 102400 to 49152 because of enabling hardware forward compatibility
[03/05/2026-01:43:54] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
```
I think it reflects to what they mention in their official documentation:
https://docs.nvidia.com/deeplearning/tensorrt/latest/_static/python-api/infer/Core/BuilderConfig.html#tensorrt.HardwareCompatibilityLevel

However, when using `tensorrt 10.15.1.29` on both Jetson and Spark, there is error as below which means `trt_hardware_compatibility_level` is not supported.

```
TensorRT: starting export with TensorRT 10.15.1.29...
[03/05/2026-01:57:32] [TRT] [I] [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 1101, GPU 107231 (MiB)
[03/05/2026-01:57:32] [TRT] [E] IBuilderConfig::setHardwareCompatibilityLevel: Error Code 3: API Usage Error (Parameter check failed, condition: hardwareCompatibilityLevel == HardwareCompatibilityLevel::kNONE. Hardware compatibility level is not supported in current platform. In setHardwareCompatibilityLevel at /_src/optimizer/api/builderConfig.cpp:813)
```

On RTX Pro 6000, using both tensorrt 10.13.3.9 and 10.15.1.29, `trt_hardware_compatibility_level` works to export a model (trtexec and Python API). However, when inferencing, these models cannot be used on Thor and Spark. The issue is the same other way around. Probably because their architecture is different (X86 vs ARM64). Because this time it complains about not supported on platform rather than mentioning about GPU compute incompatibility.

```
[03/05/2026-02:59:17] [TRT] [E] IRuntime::deserializeCudaEngine: Error Code 1: Serialization (Serialization assertion header.pad == expectedPlatformTag failed.Platform specific tag mismatch detected. TensorRT plan files are only supported on the target runtime platform they were created on. In throwUnlessHeaderOk at runtime/dispatch/runtime.cpp:46)
```

So in conclusion, what works:

- Export a tensorrt model on Jetson Thor with `trt_hardware_compatibility_level=ampere_plus` and Inference on DGX Spark given that tensorrt 10.13.3.9 is used.
- Export a tensorrt model on DGX Spark with `trt_hardware_compatibility_level=ampere_plus` and Inference on Jetson Thor given that tensorrt 10.13.3.9 is used.
- Also if the system is sharing same architecture such as Orin, `trt_hardware_compatibility_level` is not needed. Just make sure keep the same tensorrt version (10.3) at export and inference. Which means you can export on any Orin (AGX, NX, Nano) and inference on any Orin (AGX, NX, Nano).

**Comment by lakshanthad** [comment]
@onuralpszr I have made changes on this PR based on my detailed testing with Jetson Thor/ DGX Spark and Blackwell GPUs with `hardware_compatibility_level` argument. The latest change on a high level overview are as follows:

- Renamed TensorRT export arg to `hw_compat`.
- Added Thor/Spark (ARM64) guard. Apply `hw_compat` only on TensorRT 10.13.3.9. Otherwise disable with warning.
- Kept TensorRT >=10.15 check only for RT-DETR exports on Thor/Spark ARM64 when hw_compat='none'.
- Updated docs to reflect these changes.

@Laughing-q please help to review as well. I think we have been holding this PR for a while and we could potentially merge it after review from you guys. Thanks!

> @onuralpszr Here is my full report based on my testing on AGX Thor, DGX Spark and RTX Pro 6000:
> 
> On Jetson Thor and DGX Spark, `trt_hardware_compatibility_level` only works with `tensorrt 10.13.3.9`. Given that both devices are on this version of tensorrt, they work interchangeably. That is export on one and inference on the other. This works with both trtexec tool and Python API usage.
> 
> However, while exporting to engine files, there is this message:
> 
> ```
> TensorRT: building FP32 engine as yolo26n.engine
> [03/05/2026-01:43:54] [TRT] [I] Lowering maximum device shared memory from 102400 to 49152 because of enabling hardware forward compatibility
> [03/05/2026-01:43:54] [TRT] [I] Lowering maximum device shared memory from 102400 to 49152 because of enabling hardware forward compatibility
> [03/05/2026-01:43:54] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
> ```
> 
> I think it reflects to what they mention in their official documentation: https://docs.nvidia.com/deeplearning/tensorrt/latest/_static/python-api/infer/Core/BuilderConfig.html#tensorrt.HardwareCompatibilityLevel
> 
> However, when using `tensorrt 10.15.1.29` on both Jetson and Spark, there is error as below which means `trt_hardware_compatibility_level` is not supported.
> 
> ```
> TensorRT: starting export with TensorRT 10.15.1.29...
> [03/05/2026-01:57:32] [TRT] [I] [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 1101, GPU 107231 (MiB)
> [03/05/2026-01:57:32] [TRT] [E] IBuilderConfig::setHardwareCompatibilityLevel: Error Code 3: API Usage Error (Parameter check failed, condition: hardwareCompatibilityLevel == HardwareCompatibilityLevel::kNONE. Hardware compatibility level is not supported in current platform. In setHardwareCompatibilityLevel at /_src/optimizer/api/builderConfig.cpp:813)
> ```
> 
> On RTX Pro 6000, using both tensorrt 10.13.3.9 and 10.15.1.29, `trt_hardware_compatibility_level` works to export a model (trtexec and Python API). However, when inferencing, these models cannot be used on Thor and Spark. The issue is the same other way around. Probably because their architecture is different (X86 vs ARM64). Because this time it complains about not supported on platform rather than mentioning about GPU compute incompatibility.
> 
> ```
> [03/05/2026-02:59:17] [TRT] [E] IRuntime::deserializeCudaEngine: Error Code 1: Serialization (Serialization assertion header.pad == expectedPlatformTag failed.Platform specific tag mismatch detected. TensorRT plan files are only supported on the target runtime platform they were created on. In throwUnlessHeaderOk at runtime/dispatch/runtime.cpp:46)
> ```
> 
> So in conclusion, what works:
> 
> * Export a tensorrt model on Jetson Thor with `trt_hardware_compatibility_level=ampere_plus` and Inference on DGX Spark given that tensorrt 10.13.3.9 is used.
> * Export a tensorrt model on DGX Spark with `trt_hardware_compatibility_level=ampere_plus` and Inference on Jetson Thor given that tensorrt 10.13.3.9 is used.
> * Also if the system is sharing same architecture such as Orin, `trt_hardware_compatibility_level` is not needed. Just make sure keep the same tensorrt version (10.3) at export and inference. Which means you can export on any Orin (AGX, NX, Nano) and inference on any Orin (AGX, NX, Nano).

**Comment by onuralpszr** [comment]
I will do review but we should also do some benchmarks in same device export between trtexec and python usage of ours to make sure numbers are fine as well. Before add option we need to make sure what we gain and lose as well.

**Comment by lakshanthad** [comment]
Thanks @onuralpszr. Waiting for your review.

Until then I will do all the benchmarks and update in this PR!

**Comment by glenn-jocher** [comment]
Merged current `main` into this branch to clear the conflicts. All four of your files survive and the feature works — `hw_compat` reaches `DEFAULT_CFG`, the engine `Arguments` row carries it, and the `onnx2engine` plumbing is intact.

One piece of your work did **not** survive, and I couldn't restore it without reverting main, so flagging rather than guessing.

**The narrowing on the forced TensorRT upgrade was lost.**

Your branch had (`ultralytics/engine/exporter.py:883`, from your commit `7d9dc2ed5` "Add RT-DETR checking logic"):

```python
if (
    (is_jetson(jetpack=7) or (is_dgx() and ARM64))
    and isinstance(self.model.model[-1], RTDETRDecoder)
    and trt_hw_compat_level == "none"
):
    check_tensorrt("10.15")
```

The merged head now has (`ultralytics/utils/export/engine.py:234`):

```python
if (is_jetson(jetpack=7) or is_dgx()) and hw_compat == "none":
    check_tensorrt("10.15")
```

So the `hw_compat == "none"` condition survived, but the `ARM64` qualifier and the `isinstance(..., RTDETRDecoder)` restriction are gone. **Consequence on DGX Spark / Jetson Thor:** any plain `format=engine` export with `hw_compat` unset on a non-RT-DETR model still force-upgrades TensorRT to 10.15.x, which silently destroys the 10.13.3.9 install that this feature's interop depends on.

I did not restore it because main deliberately broadened that gate to `is_dgx()` in #23573 and then relocated it into `onnx2engine` in #24245 — where `self.model.model[-1]` is not visible, since the function receives an ONNX path rather than the torch model. Restoring the RT-DETR check therefore means reverting main's broadening *and* threading a new parameter through `onnx2engine`. That's a design call for you and @Laughing-q.

Two pre-existing nits, both present in your branch before the merge, not introduced by it:

- `getattr(trt.HardwareCompatibilityLevel, hw_compat.upper(), None)` dereferences `trt.HardwareCompatibilityLevel` unguarded. TensorRT <8.6 is still allowed by `check_version(trt.__version__, ">=7.0.0")` and has no such attribute, so `hw_compat=ampere_plus` raises `AttributeError` instead of the intended graceful warning.
- The TensorRT row in `docs/macros/export-table.md` lists per-format supported args and wasn't updated with `hw_compat`.
