### ISSUE TITLE
'AutoBackend' object has no attribute 'task'

### ISSUE THREAD

**Issue by Liagos** [ultralytics/ultralytics#16038]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Hello,

I have trained a custom model which I have converted and loaded to Triton server. Since I updated the ultralytics library to 8.2.87 I get the following error:

Traceback (most recent call last):
  File "my_tracker_countline.py", line 433, in <module>
    main()
  File "my_tracker_countline.py", line 223, in main
    for result in results:
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 50, in generator_context
    response = gen.send(None)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/engine/predictor.py", line 234, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/autobackend.py", line 639, in warmup
    self.forward(im)  # warmup
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/autobackend.py", line 606, in forward
    if len(self.names) == 999 and (self.task == "segment" or len(y) == 2):  # segments and names not defined
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1587, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'AutoBackend' object has no attribute 'task'

Is this a bug or am I loading the model wrong?

Thanks for your help

Regards,
Odysseas

### Environment

Orin Nano 8GB

### Minimal Reproducible Example

   # Triton server
    triton_client = InferenceServerClient(url=f'{HOST_IP}:8001', verbose=False, ssl=False)
    # Wait until model is ready
    for _ in range(10):
        with contextlib.suppress(Exception):
            assert triton_client.is_model_ready(VI_TRITON_MODEL)
            break
        time.sleep(1)

    # Load model
    my_model = YOLO(f'http://{HOST_IP}:8001/{VI_TRITON_MODEL}', task='detect')

    v_cap, gs_pipeline = get_frame_reader(DETECT_URL, WIDTH, HEIGHT, VI_FPS)
    if not v_cap.isOpened():
        os._exit(1)
    prev_frame_time = 0
    while True:
        ret_val, frame = v_cap.read()
        if not ret_val:
            frame = np.zeros((int(WIDTH), int(HEIGHT), 3), dtype=np.uint8)
            logger.warning("Waiting for stream...")
            v_cap.open(gs_pipeline, cv2.CAP_GSTREAMER)
        new_frame_time = time.time()
        fps = 1 / (new_frame_time - prev_frame_time)
        prev_frame_time = new_frame_time
        logger.debug(f'FPS:{fps}')

        if VI_MODE == 'TRACK':
            results = my_model.track(source=frame,
                                     show=False,
                                     stream=True,
                                     persist=True,
                                     classes=filter_cls,
                                     verbose=LOG_LEVEL == 'DEBUG',
                                     data=yaml_file)

            for result in results:

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Y-T-G** [comment]
You have to pass your model's `data.yaml` while loading the model:
https://github.com/ultralytics/ultralytics/issues/15003#issuecomment-2295822993

**Comment by Y-T-G** [comment]
Should also be fixed by https://github.com/ultralytics/ultralytics/pull/15883
