### ISSUE TITLE
module 'cv2' has no attribute 'imdecodemulti'

### ISSUE THREAD

**Issue by FreemanTang** [ultralytics/ultralytics#25701]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

<img width="1050" height="466" alt="Image" src="https://github.com/user-attachments/assets/97651ae2-37ec-4a98-bd1d-8237c1679df0" />

@glenn-jocher Hello, I would like to ask a question. When predicting, if the input image is .tif, cv2.imdecodemulti will be used, but the error module 'cv2' has no attribute 'imdecodemulti' will be reported. Is this method deprecated?

### Environment

Ultralytics 8.4.95
Python 3.11.13
Pytorch 2.7.1+cu128
CUDA RTX2070 8G
Window 10
opencv-python 4.6.0.66

### Minimal Reproducible Example

```
results = model.predict(
            source=args.source,
            project=project,
            # name=args.name,
            save=True,
            imgsz=args.imgsz,
            conf=args.conf,
            iou=args.iou,
            stream=True,
            workers=args.workers,
            save_txt=args.save_txt,
            device=device
        )
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @FreemanTang, thank you for your interest in Ultralytics 🚀! This is an automated response, and an Ultralytics engineer will also assist you soon.

We recommend visiting the [Docs](https://docs.ultralytics.com/) for new users, where you can find many [Python](https://docs.ultralytics.com/usage/python) and [CLI](https://docs.ultralytics.com/usage/cli) usage examples and where many common questions may already be answered.

Since this appears to be a 🐛 bug report, please provide a complete [minimum reproducible example](https://docs.ultralytics.com/help/minimum-reproducible-example). The current prediction snippet alone is not sufficient to reproduce the issue. Please include:
- The smallest possible input `.tif` image or a representative sample
- The complete script or exact CLI command
- The full traceback
- The output of `pip show ultralytics opencv-python opencv-python-headless`
- Confirmation of whether the issue persists after upgrading

If this is also a custom training ❓ question, please provide as much information as possible, including dataset image examples and training logs, and verify you are following our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips).

Join the Ultralytics community where it suits you best. For real-time chat, head to [Discord](https://discord.com/invite/ultralytics) 🎧. Prefer in-depth discussions? Check out [Discourse](https://community.ultralytics.com/). Or dive into threads on our [Subreddit](https://www.reddit.com/r/Ultralytics/) to share knowledge with the community.

## Upgrade

Upgrade to the latest `ultralytics` package including all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/) to verify your issue is not already resolved in the latest version:

```bash
pip install -U ultralytics
```

## Environments

YOLO may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo26"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml?query=event%3Aschedule) tests are currently passing. CI tests verify correct operation of all YOLO [Modes](https://docs.ultralytics.com/modes) and [Tasks](https://docs.ultralytics.com/tasks) on macOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by Y-T-G** [comment]
You can upgrade OpenCV

```
pip install opencv-python==4.7
```

**Comment by FreemanTang** [comment]
> You can upgrade OpenCV
> 
> ```
> pip install opencv-python==4.7
> ```

@Y-T-G Thanks for your reply! After upgrading opencv-python to 4.7.0.68, the module 'cv2' has no attribute 'imdecodemulti' error is no longer reported.

But got new error "Error in execution: Got invalid dimensions for input: images for the following indices index: 1 Got: 1 Expected: 3".
This error should be caused by the input image being single-channel.

My current solution is to solve it directly from the input source. All types of images are first converted into RGB format images, and then predictions are made. In this way, there is also no need to upgrade opencv-python to 4.7.0.68.

Do you have any other better suggestions?

**Comment by Y-T-G** [comment]
It seems like you're using a single-channel image with an RGB model.

You can try upgrading to latest Ultralytics and see if it's still present 

```
pip install -u ultralytics 
```
