### ISSUE TITLE
Bug in YOLOv8-OpenCV-ONNX-Python example

### ISSUE THREAD

**Issue by HoLue** [ultralytics/ultralytics#1364]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export, Other

### Bug

Use of onnx model according to main.py from
https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-OpenCV-ONNX-Python
failed

I did this on Colab, the notebook inference_onnx_230310a.ipynb is in the zip arcive
[inference_onnx_230310a.zip](https://github.com/ultralytics/ultralytics/files/10943960/inference_onnx_230310a.zip)

My exported onnx file:
[yolov8n.zip](https://github.com/ultralytics/ultralytics/files/10944039/yolov8n.zip)

I get the same error when I used the model on my local windows 10 pc with main_hl01.zip in the zip archive
[main_hl01.zip](https://github.com/ultralytics/ultralytics/files/10944001/main_hl01.zip)

Also I get the same error, whe I use the cpp code from 
https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-CPP-Inference
The whole VS project is here:
[CalcInf01.zip](https://github.com/ultralytics/ultralytics/files/10944030/CalcInf01.zip)

### Environment

- Ultralytics YOLOv8.0.52 🚀 Python-3.9.16 torch-1.13.1+cu116 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 31.0/166.8 GB disk)
- Linux-5.10.147+-x86_64-with-glibc2.31
- Python 3.9.16

### Minimal Reproducible Example

see Colab notebook above in inference_onnx_230310a.zip

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@HoLue perhaps the author of the example 
@frdteknikelektro can help with your bug report.

**Comment by knoppmyth** [comment]
Perhaps posting details about the error you're getting.

**Comment by HoLue** [comment]
Thanks, error is given in the ipynb, but of course, here it is (other errors for doing the python or cpp on my pc are similar):

error                                     Traceback (most recent call last)
<ipython-input-4-d74c3382b1b6> in <module>
     80 
     81 
---> 82 main()

<ipython-input-4-d74c3382b1b6> in main()
     27         return
     28 
---> 29     model: cv2.dnn.Net = cv2.dnn.readNetFromONNX(model_path)
     30     original_image: np.ndarray = cv2.imread(str(ROOT / 'assets/bus.jpg'))
     31     [height, width, _] = original_image.shape

error: OpenCV(4.6.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1040: error: (-2:Unspecified error) in function 'handleNode'
> Node [Add@ai.onnx]:(onnx_node!/model.22/Add) parse error: OpenCV(4.6.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1464: error: (-215:Assertion failed) blob_0.size == blob_1.size in function 'parseBias'

**Comment by frdteknikelektro** [comment]
Try to use OpenCV 4.7

**Comment by HoLue** [comment]
Yes, at least on Colab it works with OpenCV 4.7. Thanks!

Just as remark / suggestion:
May it be an idea to check OpenCV version in the code to avoid this problem?
Something like:
`assert cv2.__version__ >= '4.7', 'Please update OpenCV version to 4.7 or newer!'`

Other problem (cpp) I have to check, probably same

**Comment by weihong0827** [comment]
I have the same issue with opencv-python==4.7.0.72

My error is :: OpenCV(4.7.0) /Users/xperience/GHA-OCV-Python/_work/opencv-python/opencv-python/opencv/modules/dnn/src/layers/reshape_layer.cpp:109: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'computeShapeByReshapeMask'

I have tried exporting both v5 and v8 models and both didn't work, I use cv2.dnn.readNetFromONNX(path_to_model)

**Comment by AyushExel** [comment]
I verified the example on my system so it might be some version compatibility problem with your setup. Let's wait for the author of the example to respond.

**Comment by frdteknikelektro** [comment]
@weihong0827 
Make sure you include parameter `opset` when converting model
yolo export model=yolov8n.pt format=onnx opset=12

**Comment by HoLue** [comment]
@frdteknikelektro
Now, I tried my local system (not Colab). I changed the OpenCV to version 4.7.0 - but the error remains (except of change of given OpenCV version number):

PS D:\Di\Z_InfosTestTry\Z_Programmier\Ai\Ai04_YOLOv8\y8_03\CalcInference\Python\cip01> python .\main_hl01.py
Traceback (most recent call last):
  File "D:\Di\Z_InfosTestTry\Z_Programmier\Ai\Ai04_YOLOv8\y8_03\CalcInference\Python\cip01\main_hl01.py", line 81, in <module>
    main()
  File "D:\Di\Z_InfosTestTry\Z_Programmier\Ai\Ai04_YOLOv8\y8_03\CalcInference\Python\cip01\main_hl01.py", line 73, in main
    cv2.imshow('image', original_image)
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1272: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'

My file main_hl01.py can be found in the zip archive:
[main_hl01.zip](https://github.com/ultralytics/ultralytics/files/10959008/main_hl01.zip)

**Comment by frdteknikelektro** [comment]
I think this one is related to opencv library not the rnn part.
Maybe you need to reinstall depedencies on your local
Are you using virtual enviroment?

**Comment by HoLue** [comment]
@frdteknikelektro 
On my local system (not Colab) it works with python with OpenCV 4.7, too. (Cpp I have to check...)

**Comment by weihong0827** [comment]
> 

Thanks this helps me load the file successfully

**Comment by weihong0827** [comment]
> @weihong0827 Make sure you include parameter `opset` when converting model
> 
> ```shell
> yolo export model=yolov8n.pt format=onnx opset=12
> ```

Thanks this helps me load the file successfully

**Comment by HoLue** [comment]
@frdteknikelektro 
Is there an example for exported onnx model for segmentation (and classification), too? This would help me very much!

**Comment by frdteknikelektro** [comment]
I haven't try for segmentation and classification

**Comment by pderrenger** [comment]
@frdteknikelektro thank you for sharing the solution and providing feedback on your experience. We're glad that you were able to successfully load the file. If you need further assistance regarding segmentation and classification, feel free to ask. We're here to help!
