### ISSUE TITLE
Does onnx export include NMS post-processing?

### ISSUE THREAD

**Issue by SebastianJanampa** [ultralytics/ultralytics#21013]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/orgs/ultralytics/discussions) and found no similar questions.

### Question

Hello,

I am trying to benchmark yolo11-pose and yolov8-pose. I saw some github repos and they export the model to onnx and then manually add the nms postprocessing as shown below
```python
def yolo_insert_nms(
    path, score_threshold=0.01, iou_threshold=0.7, max_output_boxes=300, simplify=False
):
    """
    http://www.xavierdupre.fr/app/onnxcustom/helpsphinx/api/onnxops/onnx__EfficientNMS_TRT.html
    https://huggingface.co/spaces/muttalib1326/Punjabi_Character_Detection/blob/3dd1e17054c64e5f6b2254278f96cfa2bf418cd4/utils/add_nms.py
    """
    onnx_model = onnx.load(path)

    if simplify:
        from onnxsim import simplify

        onnx_model, _ = simplify(onnx_model, overwrite_input_shapes={"image": [1, 3, 640, 640]})

    graph = onnx_graphsurgeon.import_onnx(onnx_model)
    graph.toposort()
    graph.fold_constants()
    graph.cleanup()

    topk = max_output_boxes
    attrs = OrderedDict(
        plugin_version="1",
        background_class=-1,
        max_output_boxes=topk,
        score_threshold=score_threshold,
        iou_threshold=iou_threshold,
        score_activation=False,
        box_coding=0,
    )

    outputs = [
        onnx_graphsurgeon.Variable("num_dets", np.int32, [-1, 1]),
        onnx_graphsurgeon.Variable("det_boxes", np.float32, [-1, topk, 4]),
        onnx_graphsurgeon.Variable("det_scores", np.float32, [-1, topk]),
        onnx_graphsurgeon.Variable("det_classes", np.int32, [-1, topk]),
    ]

    graph.layer(
        op="EfficientNMS_TRT",
        name="batched_nms",
        inputs=[graph.outputs[0], graph.outputs[1]],
        outputs=outputs,
        attrs=attrs,
    )

    graph.outputs = outputs
    graph.cleanup().toposort()

    onnx.save(onnx_graphsurgeon.export_onnx(graph), "yolo_w_nms.onnx")
```

This approch works for object detect (i dont know if it is the best approach but it works), but it doesnt for pose estimation. So my question is, is there any way i can add the NMS to my generated onnx engine when i export yolo11-pose using the ultralytics library? my final goal is to generate trt engines from the exported onnx engines

Thank,
Sebastian

**Comment by UltralyticsAssistant** [comment]
👋 Hello @SebastianJanampa, thank you for reaching out and for your interest in Ultralytics 🚀! This is an automated response to help you get started—an Ultralytics engineer will assist you here soon.

We recommend visiting the [Docs](https://docs.ultralytics.com/) for detailed information, including [Python](https://docs.ultralytics.com/usage/python/) and [CLI](https://docs.ultralytics.com/usage/cli/) examples. Many frequently asked questions are also answered there.

If this is a 🐛 Bug Report, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum-reproducible-example/) to help us debug your issue.

If your question relates to custom training or export, please include as much relevant detail as possible (such as your export command, ONNX files, and logs), and ensure you are following our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).

You're welcome to join the Ultralytics community for further discussion and support:
- Real-time chat: [Discord](https://discord.com/invite/ultralytics) 🎧
- In-depth forums: [Discourse](https://community.ultralytics.com/)
- Community threads: [Subreddit](https://reddit.com/r/Ultralytics)

## Upgrade

To make sure your issue is not already resolved, upgrade to the latest `ultralytics` package and all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/):

```bash
pip install -U ultralytics
```

## Environments

YOLO models can be run in the following up-to-date, verified environments (with all dependencies, including [CUDA](https://developer.nvidia.com/cuda-zone)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/), and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

## Status

<a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml?query=event%3Aschedule"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml/badge.svg" alt="Ultralytics CI"></a>

If this badge is green, all [Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yml?query=event%3Aschedule) tests are currently passing. These CI tests verify correct operation of all YOLO [Modes](https://docs.ultralytics.com/modes/) and [Tasks](https://docs.ultralytics.com/tasks/) on macOS, Windows, and Ubuntu every 24 hours and on every commit.

Thank you again for your question and for using Ultralytics!

**Comment by Y-T-G** [comment]
It will add NMS if you use `nms=True`


https://docs.ultralytics.com/modes/export/#arguments

**Comment by SebastianJanampa** [comment]
Hi @Y-T-G
I tried that but when i try to export to tensorrt it doesnt work. Here is the error log
```shell
&&&& RUNNING TensorRT.trtexec [TensorRT v8603] # trtexec --onnx=yolo11n-pose.onnx --saveEngine=yolo11n-pose.engine --fp16
[06/11/2025-15:24:43] [I] === Model Options ===
[06/11/2025-15:24:43] [I] Format: ONNX
[06/11/2025-15:24:43] [I] Model: yolo11n-pose.onnx
[06/11/2025-15:24:43] [I] Output:
[06/11/2025-15:24:43] [I] === Build Options ===
[06/11/2025-15:24:43] [I] Max batch: explicit batch
[06/11/2025-15:24:43] [I] Memory Pools: workspace: default, dlaSRAM: default, dlaLocalDRAM: default, dlaGlobalDRAM: default
[06/11/2025-15:24:43] [I] minTiming: 1
[06/11/2025-15:24:43] [I] avgTiming: 8
[06/11/2025-15:24:43] [I] Precision: FP32+FP16
[06/11/2025-15:24:43] [I] LayerPrecisions: 
[06/11/2025-15:24:43] [I] Layer Device Types: 
[06/11/2025-15:24:43] [I] Calibration: 
[06/11/2025-15:24:43] [I] Refit: Disabled
[06/11/2025-15:24:43] [I] Version Compatible: Disabled
[06/11/2025-15:24:43] [I] ONNX Native InstanceNorm: Disabled
[06/11/2025-15:24:43] [I] TensorRT runtime: full
[06/11/2025-15:24:43] [I] Lean DLL Path: 
[06/11/2025-15:24:43] [I] Tempfile Controls: { in_memory: allow, temporary: allow }
[06/11/2025-15:24:43] [I] Exclude Lean Runtime: Disabled
[06/11/2025-15:24:43] [I] Sparsity: Disabled
[06/11/2025-15:24:43] [I] Safe mode: Disabled
[06/11/2025-15:24:43] [I] Build DLA standalone loadable: Disabled
[06/11/2025-15:24:43] [I] Allow GPU fallback for DLA: Disabled
[06/11/2025-15:24:43] [I] DirectIO mode: Disabled
[06/11/2025-15:24:43] [I] Restricted mode: Disabled
[06/11/2025-15:24:43] [I] Skip inference: Disabled
[06/11/2025-15:24:43] [I] Save engine: yolo11n-pose.engine
[06/11/2025-15:24:43] [I] Load engine: 
[06/11/2025-15:24:43] [I] Profiling verbosity: 0
[06/11/2025-15:24:43] [I] Tactic sources: Using default tactic sources
[06/11/2025-15:24:43] [I] timingCacheMode: local
[06/11/2025-15:24:43] [I] timingCacheFile: 
[06/11/2025-15:24:43] [I] Heuristic: Disabled
[06/11/2025-15:24:43] [I] Preview Features: Use default preview flags.
[06/11/2025-15:24:43] [I] MaxAuxStreams: -1
[06/11/2025-15:24:43] [I] BuilderOptimizationLevel: -1
[06/11/2025-15:24:43] [I] Input(s)s format: fp32:CHW
[06/11/2025-15:24:43] [I] Output(s)s format: fp32:CHW
[06/11/2025-15:24:43] [I] Input build shapes: model
[06/11/2025-15:24:43] [I] Input calibration shapes: model
[06/11/2025-15:24:43] [I] === System Options ===
[06/11/2025-15:24:43] [I] Device: 0
[06/11/2025-15:24:43] [I] DLACore: 
[06/11/2025-15:24:43] [I] Plugins:
[06/11/2025-15:24:43] [I] setPluginsToSerialize:
[06/11/2025-15:24:43] [I] dynamicPlugins:
[06/11/2025-15:24:43] [I] ignoreParsedPluginLibs: 0
[06/11/2025-15:24:43] [I] 
[06/11/2025-15:24:43] [I] === Inference Options ===
[06/11/2025-15:24:43] [I] Batch: Explicit
[06/11/2025-15:24:43] [I] Input inference shapes: model
[06/11/2025-15:24:43] [I] Iterations: 10
[06/11/2025-15:24:43] [I] Duration: 3s (+ 200ms warm up)
[06/11/2025-15:24:43] [I] Sleep time: 0ms
[06/11/2025-15:24:43] [I] Idle time: 0ms
[06/11/2025-15:24:43] [I] Inference Streams: 1
[06/11/2025-15:24:43] [I] ExposeDMA: Disabled
[06/11/2025-15:24:43] [I] Data transfers: Enabled
[06/11/2025-15:24:43] [I] Spin-wait: Disabled
[06/11/2025-15:24:43] [I] Multithreading: Disabled
[06/11/2025-15:24:43] [I] CUDA Graph: Disabled
[06/11/2025-15:24:43] [I] Separate profiling: Disabled
[06/11/2025-15:24:43] [I] Time Deserialize: Disabled
[06/11/2025-15:24:43] [I] Time Refit: Disabled
[06/11/2025-15:24:43] [I] NVTX verbosity: 0
[06/11/2025-15:24:43] [I] Persistent Cache Ratio: 0
[06/11/2025-15:24:43] [I] Inputs:
[06/11/2025-15:24:43] [I] === Reporting Options ===
[06/11/2025-15:24:43] [I] Verbose: Disabled
[06/11/2025-15:24:43] [I] Averages: 10 inferences
[06/11/2025-15:24:43] [I] Percentiles: 90,95,99
[06/11/2025-15:24:43] [I] Dump refittable layers:Disabled
[06/11/2025-15:24:43] [I] Dump output: Disabled
[06/11/2025-15:24:43] [I] Profile: Disabled
[06/11/2025-15:24:43] [I] Export timing to JSON file: 
[06/11/2025-15:24:43] [I] Export output to JSON file: 
[06/11/2025-15:24:43] [I] Export profile to JSON file: 
[06/11/2025-15:24:43] [I] 
[06/11/2025-15:24:44] [I] === Device Information ===
[06/11/2025-15:24:44] [I] Selected Device: Tesla V100-SXM2-16GB
[06/11/2025-15:24:44] [I] Compute Capability: 7.0
[06/11/2025-15:24:44] [I] SMs: 80
[06/11/2025-15:24:44] [I] Device Global Memory: 16144 MiB
[06/11/2025-15:24:44] [I] Shared Memory per SM: 96 KiB
[06/11/2025-15:24:44] [I] Memory Bus Width: 4096 bits (ECC enabled)
[06/11/2025-15:24:44] [I] Application Compute Clock Rate: 1.53 GHz
[06/11/2025-15:24:44] [I] Application Memory Clock Rate: 0.877 GHz
[06/11/2025-15:24:44] [I] 
[06/11/2025-15:24:44] [I] Note: The application clock rates do not reflect the actual clock rates that the GPU is currently running at.
[06/11/2025-15:24:44] [I] 
[06/11/2025-15:24:44] [I] TensorRT version: 8.6.3
[06/11/2025-15:24:44] [I] Loading standard plugins
[06/11/2025-15:24:44] [I] [TRT] [MemUsageChange] Init CUDA: CPU +1, GPU +0, now: CPU 24, GPU 309 (MiB)
[06/11/2025-15:24:49] [I] [TRT] [MemUsageChange] Init builder kernel library: CPU +428, GPU +74, now: CPU 529, GPU 383 (MiB)
[06/11/2025-15:24:49] [I] Start parsing network model.
[06/11/2025-15:24:49] [I] [TRT] ----------------------------------------------------------------
[06/11/2025-15:24:49] [I] [TRT] Input filename:   yolo11n-pose.onnx
[06/11/2025-15:24:49] [I] [TRT] ONNX IR version:  0.0.9
[06/11/2025-15:24:49] [I] [TRT] Opset version:    19
[06/11/2025-15:24:49] [I] [TRT] Producer name:    pytorch
[06/11/2025-15:24:49] [I] [TRT] Producer version: 2.7.1
[06/11/2025-15:24:49] [I] [TRT] Domain:           
[06/11/2025-15:24:49] [I] [TRT] Model version:    0
[06/11/2025-15:24:49] [I] [TRT] Doc string:       
[06/11/2025-15:24:49] [I] [TRT] ----------------------------------------------------------------
[06/11/2025-15:24:49] [W] [TRT] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[06/11/2025-15:24:49] [W] [TRT] onnx2trt_utils.cpp:400: One or more weights outside the range of INT32 was clamped
[06/11/2025-15:24:49] [W] [TRT] Tensor DataType is determined at build time for tensors not marked as input or output.
[06/11/2025-15:24:49] [E] Error[4]: [gatherNode.cpp::computeGatherOutputExtents::76] Error Code 4: Internal Error (/Gather_2: rank of data tensor must be greater than or equal to 1)
[06/11/2025-15:24:49] [E] [TRT] ModelImporter.cpp:768: While parsing node number 360 [Gather -> "/Gather_2_output_0"]:
[06/11/2025-15:24:49] [E] [TRT] ModelImporter.cpp:769: --- Begin node ---
[06/11/2025-15:24:49] [E] [TRT] ModelImporter.cpp:770: input: "/ReduceMax_output_0"
input: "/model/model.10/m/m.0/attn/Constant_output_0"
output: "/Gather_2_output_0"
name: "/Gather_2"
op_type: "Gather"
attribute {
  name: "axis"
  i: 0
  type: INT
}

[06/11/2025-15:24:49] [E] [TRT] ModelImporter.cpp:771: --- End node ---
[06/11/2025-15:24:49] [E] [TRT] ModelImporter.cpp:774: ERROR: ModelImporter.cpp:195 In function parseGraph:
[6] Invalid Node - /Gather_2
[gatherNode.cpp::computeGatherOutputExtents::76] Error Code 4: Internal Error (/Gather_2: rank of data tensor must be greater than or equal to 1)
[06/11/2025-15:24:49] [E] Failed to parse onnx file
[06/11/2025-15:24:49] [I] Finished parsing network model. Parse time: 0.0656091
[06/11/2025-15:24:49] [E] Parsing model failed
[06/11/2025-15:24:49] [E] Failed to create engine from model or file.
[06/11/2025-15:24:49] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8603] # trtexec --onnx=yolo11n-pose.onnx --saveEngine=yolo11n-pose.engine --fp16
```

Nevertheless, using `nms=False` works fine.

**Comment by Y-T-G** [comment]
You should export to TensorRT with Ultralytics

**Comment by SebastianJanampa** [comment]
Hi @Y-T-G 

I also export using ultralitycs
```shell
yolo export model=yolo11n-pose.pt format=engine nms=True
```

This is the error log
```
WARNING ⚠️ user config directory '/root/.config/Ultralytics' is not writeable, defaulting to '/tmp' or CWD.Alternatively you can define a YOLO_CONFIG_DIR environment variable for this path.
WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics 8.3.153 🚀 Python-3.10.12 torch-2.7.1+cu126 CUDA:0 (Tesla V100-SXM2-16GB, 16144MiB)

YOLO11n-pose summary (fused): 109 layers, 2,866,468 parameters, 0 gradients, 7.4 GFLOPs

PyTorch: starting from 'yolo11n-pose.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 57) (6.0 MB)

ONNX: starting export with onnx 1.17.0 opset 19...
ONNX: slimming with onnxslim 0.1.57...
ONNX: export success ✅ 1.8s, saved as 'yolo11n-pose.onnx' (11.3 MB)

TensorRT: starting export with TensorRT 8.6.3...
[06/11/2025-17:04:35] [TRT] [I] [MemUsageChange] Init CUDA: CPU +2, GPU +0, now: CPU 727, GPU 497 (MiB)
[06/11/2025-17:04:40] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +428, GPU +74, now: CPU 1231, GPU 571 (MiB)
[06/11/2025-17:04:40] [TRT] [I] ----------------------------------------------------------------
[06/11/2025-17:04:40] [TRT] [I] Input filename:   yolo11n-pose.onnx
[06/11/2025-17:04:40] [TRT] [I] ONNX IR version:  0.0.9
[06/11/2025-17:04:40] [TRT] [I] Opset version:    19
[06/11/2025-17:04:40] [TRT] [I] Producer name:    pytorch
[06/11/2025-17:04:40] [TRT] [I] Producer version: 2.7.1
[06/11/2025-17:04:40] [TRT] [I] Domain:           
[06/11/2025-17:04:40] [TRT] [I] Model version:    0
[06/11/2025-17:04:40] [TRT] [I] Doc string:       
[06/11/2025-17:04:40] [TRT] [I] ----------------------------------------------------------------
[06/11/2025-17:04:40] [TRT] [W] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[06/11/2025-17:04:40] [TRT] [W] onnx2trt_utils.cpp:400: One or more weights outside the range of INT32 was clamped
[06/11/2025-17:04:40] [TRT] [W] Tensor DataType is determined at build time for tensors not marked as input or output.
[06/11/2025-17:04:40] [TRT] [E] [gatherNode.cpp::computeGatherOutputExtents::76] Error Code 4: Internal Error (/Gather_2: rank of data tensor must be greater than or equal to 1)
[06/11/2025-17:04:40] [TRT] [E] ModelImporter.cpp:768: While parsing node number 360 [Gather -> "/Gather_2_output_0"]:
[06/11/2025-17:04:40] [TRT] [E] ModelImporter.cpp:769: --- Begin node ---
[06/11/2025-17:04:40] [TRT] [E] ModelImporter.cpp:770: input: "/ReduceMax_output_0"
input: "/model/model.10/m/m.0/attn/Constant_output_0"
output: "/Gather_2_output_0"
name: "/Gather_2"
op_type: "Gather"
attribute {
  name: "axis"
  i: 0
  type: INT
}

[06/11/2025-17:04:40] [TRT] [E] ModelImporter.cpp:771: --- End node ---
[06/11/2025-17:04:40] [TRT] [E] ModelImporter.cpp:774: ERROR: ModelImporter.cpp:195 In function parseGraph:
[6] Invalid Node - /Gather_2
[gatherNode.cpp::computeGatherOutputExtents::76] Error Code 4: Internal Error (/Gather_2: rank of data tensor must be greater than or equal to 1)
ERROR ❌ TensorRT: export failure 7.1s: failed to load ONNX file: yolo11n-pose.onnx
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 983, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 734, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 500, in __call__
    f[1], _ = self.export_engine(dla=dla)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 197, in outer_func
    raise e
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 192, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 938, in export_engine
    export_engine(
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/utils/export.py", line 127, in export_engine
    raise RuntimeError(f"failed to load ONNX file: {onnx_file}")
RuntimeError: failed to load ONNX file: yolo11n-pose.onnx
```

**Comment by Y-T-G** [comment]
You probably need to upgrade your TensorRT version 

`pip install -U tensorrt`

**Comment by SebastianJanampa** [comment]
after adding that command. I got the following error
```shell
WARNING ⚠️ user config directory '/root/.config/Ultralytics' is not writeable, defaulting to '/tmp' or CWD.Alternatively you can define a YOLO_CONFIG_DIR environment variable for this path.
WARNING ⚠️ TensorRT requires GPU export, automatically assigning device=0
Ultralytics 8.3.153 🚀 Python-3.10.12 torch-2.7.1+cu126 CUDA:0 (Tesla V100-SXM2-16GB, 16144MiB)
YOLO11n-pose summary (fused): 109 layers, 2,866,468 parameters, 0 gradients, 7.4 GFLOPs

PyTorch: starting from 'yolo11n-pose.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 57) (6.0 MB)

ONNX: starting export with onnx 1.17.0 opset 19...
ONNX: slimming with onnxslim 0.1.57...
ONNX: export success ✅ 1.8s, saved as 'yolo11n-pose.onnx' (11.3 MB)
ERROR ❌ TensorRT: export failure 1.8s: module 'tensorrt' has no attribute '__version__'
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 983, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 734, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 500, in __call__
    f[1], _ = self.export_engine(dla=dla)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 197, in outer_func
    raise e
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 192, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/exporter.py", line 931, in export_engine
    check_version(trt.__version__, ">=7.0.0", hard=True)
AttributeError: module 'tensorrt' has no attribute '__version__'
```

I run this on a TeslaV100 using tensorRT=8.6.3

When I use a A10 and TensorRT=10.11.0, the export works without any problem. So my guess is that there may be a bug in the Ultralytics code that may not allow exporting the models using old tensorrt version. 

```
[06/11/2025-17:04:40] [TRT] [E] [gatherNode.cpp::computeGatherOutputExtents::76] Error Code 4: Internal Error (/Gather_2: rank of data tensor must be greater than or equal to 1)
[06/11/2025-17:04:40] [TRT] [E] ModelImporter.cpp:768: While parsing node number 360 [Gather -> "/Gather_2_output_0"]:
[06/11/2025-17:04:40] [TRT] [E] ModelImporter.cpp:769: --- Begin node ---
[06/11/2025-17:04:40] [TRT] [E] ModelImporter.cpp:770: input: "/ReduceMax_output_0"
input: "/model/model.10/m/m.0/attn/Constant_output_0"
output: "/Gather_2_output_0"
name: "/Gather_2"
op_type: "Gather"
attribute {
  name: "axis"
  i: 0
  type: INT
}

**Comment by glenn-jocher** [comment]
Yes, ONNX export includes NMS post-processing when you use `nms=True` - the [NMSModel wrapper](https://docs.ultralytics.com/reference/engine/exporter/#ultralytics.engine.exporter.NMSModel) is automatically applied during export to add the NMS operations to your model.

The issue you're experiencing is a TensorRT version compatibility problem. The Gather operation in the NMS-enabled ONNX model requires TensorRT 10+ to parse correctly, which explains why it works on your A10 with TensorRT 10.11.0 but fails on Tesla V100 with TensorRT 8.6.3. Unfortunately, older TensorRT versions don't support all the ONNX operations generated by the NMS wrapper for pose models.

Your options are either upgrade to TensorRT 10+ or export without NMS (`nms=False`) and handle post-processing separately in your inference pipeline.

**Comment by SebastianJanampa** [comment]
Hi @glenn-jocher 

On the ultralytics, the team has reported the latency on a A100 using TensorRt 6.8.1. here ins the [link](https://docs.ultralytics.com/integrations/tensorrt/#nvidia-a100). So, i dont think it is a tensorrt problem

**Comment by Y-T-G** [comment]
The reported latency isn't with NMS exported model. This seems like an issue with TensorRT, otherwise using a higher version shouldn't have fixed the issue. Besides that, the original ONNX model which is being converted works completely fine.

You can try the following workaround to see if it works:

```python
from ultralytics.engine.exporter import NMSModel
import torch

def forward(self, x):
    """
    Perform inference with NMS post-processing. Supports Detect, Segment, OBB and Pose.

    Args:
        x (torch.Tensor): The preprocessed tensor with shape (N, 3, H, W).

    Returns:
        (torch.Tensor): List of detections, each an (N, max_det, 4 + 2 + extra_shape) Tensor where N is the
            number of detections after NMS.
    """
    from functools import partial

    from torchvision.ops import nms

    preds = self.model(x)
    pred = preds[0] if isinstance(preds, tuple) else preds
    kwargs = dict(device=pred.device, dtype=pred.dtype)
    bs = pred.shape[0]
    pred = pred.transpose(-1, -2)  # shape(1,84,6300) to shape(1,6300,84)
    extra_shape = pred.shape[-1] - (4 + len(self.model.names))  # extras from Segment, OBB, Pose
    if self.args.dynamic and self.args.batch > 1:  # batch size needs to always be same due to loop unroll
        pad = torch.zeros(torch.max(torch.tensor(self.args.batch - bs), torch.tensor(0)), *pred.shape[1:], **kwargs)
        pred = torch.cat((pred, pad))
    boxes, scores, extras = pred.split([4, len(self.model.names), extra_shape], dim=2)
    scores, classes = scores.max(dim=-1, keepdim=True)
    self.args.max_det = min(pred.shape[1], self.args.max_det)  # in case num_anchors < max_det
    # (N, max_det, 4 coords + 1 class score + 1 class label + extra_shape).
    out = torch.zeros(bs, self.args.max_det, boxes.shape[-1] + 2 + extra_shape, **kwargs)
    for i in range(bs):
        box, cls, score, extra = boxes[i], classes[i], scores[i], extras[i]
        mask = (score > self.args.conf).squeeze()
        if self.is_tf:
            # TFLite GatherND error if mask is empty
            score *= mask
            # Explicit length otherwise reshape error, hardcoded to `self.args.max_det * 5`
            mask = score.topk(min(self.args.max_det * 5, score.shape[0])).indices
        box, score, cls, extra = box[mask], score[mask], cls[mask], extra[mask]
        nmsbox = box.clone()
        # `8` is the minimum value experimented to get correct NMS results for obb
        multiplier = 8 if self.obb else 1
        # Normalize boxes for NMS since large values for class offset causes issue with int8 quantization
        if self.args.format == "tflite":  # TFLite is already normalized
            nmsbox *= multiplier
        else:
            nmsbox = multiplier * nmsbox / torch.tensor(x.shape[2:], **kwargs).max()
        if not self.args.agnostic_nms:  # class-specific NMS
            end = 2 if self.obb else 4
            # fully explicit expansion otherwise reshape error
            # large max_wh causes issues when quantizing
            cls_offset = cls.reshape(-1, 1).expand(nmsbox.shape[0], end)
            offbox = nmsbox[:, :end] + cls_offset * multiplier
            nmsbox = torch.cat((offbox, nmsbox[:, end:]), dim=-1)
        nms_fn = (
            partial(
                nms_rotated,
                use_triu=not (
                    self.is_tf
                    or (self.args.opset or 14) < 14
                    or (self.args.format == "openvino" and self.args.int8)  # OpenVINO int8 error with triu
                ),
            )
            if self.obb
            else nms
        )
        keep = nms_fn(
            torch.cat([nmsbox, extra], dim=-1) if self.obb else nmsbox,
            score.squeeze(),
            self.args.iou,
        )[: self.args.max_det]
        dets = torch.cat(
            [box[keep], score[keep], cls[keep].to(out.dtype), extra[keep]], dim=-1
        )
        # Zero-pad to max_det size to avoid reshape error
        pad = (0, 0, 0, self.args.max_det - dets.shape[0])
        out[i] = torch.nn.functional.pad(dets, pad)
    return (out[:bs], preds[1]) if self.model.task == "segment" else out[:bs]

NMSModel.forward = forward

from ultralytics import YOLO

model = YOLO("yolo11n-pose.pt")
model.export(format="engine", nms=True)
```

**Comment by SebastianJanampa** [comment]
@Y-T-G 
I tried your code, but unfortunately, it didn't work. 
So just to confirm, any of the reported times on the ultralytics website include nms, right?
May I asked why? I dont think it is a fair comparison against other models (like DETR) since NMS will increase the latency.

**Comment by Y-T-G** [comment]
No, NMS is not included. It's just the time of model inference without NMS.

**Comment by SebastianJanampa** [comment]
Ok. Thanks

**Comment by glenn-jocher** [comment]
You're welcome! Just to clarify for future reference - you can still use NMS post-processing with older TensorRT versions by exporting without `nms=True` and implementing NMS in your inference pipeline instead, which gives you more control over the process anyway.
