### PR TITLE
Warn users to avoid Python 3.13+ in Quick Start

### LINKED ISSUE #21937: AttributeError: module 'tensorflow._api.v2.compat.v2.__internal__' has no attribute 'register_load_context_function'. Did you mean: 'register_call_context_function'?
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

Hi,

I've trained a network with Yolov11 (ultralytics==8.3.189) with 

`yolo task=detect mode=train data=dataset.yaml epochs=1000 imgsz=800 model=yolo11n.pt hsv_h=0.03 hsv_s=0.6 hsv_v=0.5 degrees=180 shear=30 perspective=0.0001 fliplr=1 mosaic=0.1 mixup=0.1 cutmix=0.1 copy_paste=0.1 batch=-1`

and basically it worked as well, but at the end this happens:

```
1000 epochs completed in 51.847 hours.
Optimizer stripped from runs/detect/train3/weights/last.pt, 5.6MB
Optimizer stripped from runs/detect/train3/weights/best.pt, 5.6MB

Validating runs/detect/train3/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.13.5 torch-2.8.0+cu128 CUDA:0 (NVIDIA GeForce RTX 4060 Ti, 16068MiB)
YOLO11n summary (fused): 100 layers, 2,593,267 parameters, 0 gradients, 6.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 4.6it/s 0.9s
/home/norman/.yolov11_venv/lib/python3.13/site-packages/ultralytics/utils/metrics.py:668: RuntimeWarning: Mean of empty slice.
  ax.plot(px, py.mean(1), linewidth=3, color="blue", label=f"all classes {ap[:, 0].mean():.3f} mAP@0.5")
/home/norman/.yolov11_venv/lib/python3.13/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/norman/.yolov11_venv/lib/python3.13/site-packages/ultralytics/utils/metrics.py:713: RuntimeWarning: Mean of empty slice.
  y = smooth(py.mean(0), 0.1)
/home/norman/.yolov11_venv/lib/python3.13/site-packages/numpy/_core/_methods.py:137: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/home/norman/.yolov11_venv/lib/python3.13/site-packages/ultralytics/utils/metrics.py:713: RuntimeWarning: Mean of empty slice.
  y = smooth(py.mean(0), 0.1)
/home/norman/.yolov11_venv/lib/python3.13/site-packages/numpy/_core/_methods.py:137: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/home/norman/.yolov11_venv/lib/python3.13/site-packages/ultralytics/utils/metrics.py:713: RuntimeWarning: Mean of empty slice.
  y = smooth(py.mean(0), 0.1)
/home/norman/.yolov11_venv/lib/python3.13/site-packages/numpy/_core/_methods.py:137: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/home/norman/.yolov11_venv/lib/python3.13/site-packages/ultralytics/utils/metrics.py:850: RuntimeWarning: Mean of empty slice.
  i = smooth(f1_curve.mean(0), 0.1).argmax()  # max F1 index
                   all        200          0          0          0          0          0
WARNING ⚠ no labels found in detect set, can not compute metrics without labels
Speed: 0.3ms preprocess, 2.2ms inference, 0.0ms loss, 0.8ms postprocess per image
Results saved to runs/detect/train3
💡 Learn more at https://docs.ultralytics.com/modes/train
Ultralytics 8.3.189 🚀 Python-3.13.5 torch-2.8.0+cu128 CPU (Intel Xeon W-2155 3.30GHz)
💡 ProTip: Export to OpenVINO format for best performance on Intel hardware. Learn more at https://docs.ultralytics.com/integrations/openvino/
YOLO11n summary (fused): 100 layers, 2,593,267 parameters, 0 gradients, 6.4 GFLOPs

PyTorch: starting from 'runs/detect/train/weights/best.pt' with input shape (1, 3, 800, 800) BCHW and output shape(s) (1, 61, 13125) (10.4 MB)
requirements: Ultralytics requirement ['tensorflow>=2.0.0'] not found, attempting AutoUpdate...
Collecting tensorflow>=2.0.0
  Downloading tensorflow-2.20.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
Collecting absl-py>=1.0.0 (from tensorflow>=2.0.0)
  Downloading absl_py-2.3.1-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow>=2.0.0)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=24.3.25 (from tensorflow>=2.0.0)
  Downloading flatbuffers-25.2.10-py2.py3-none-any.whl.metadata (875 bytes)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow>=2.0.0)
  Downloading gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
Collecting google_pasta>=0.1.1 (from tensorflow>=2.0.0)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow>=2.0.0)
  Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow>=2.0.0)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from tensorflow>=2.0.0) (25.0)
Requirement already satisfied: protobuf>=5.28.0 in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from tensorflow>=2.0.0) (6.32.0)
Requirement already satisfied: requests<3,>=2.21.0 in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from tensorflow>=2.0.0) (2.32.5)
Requirement already satisfied: setuptools in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from tensorflow>=2.0.0) (80.9.0)
Requirement already satisfied: six>=1.12.0 in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from tensorflow>=2.0.0) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow>=2.0.0)
  Downloading termcolor-3.1.0-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from tensorflow>=2.0.0) (4.15.0)
Collecting wrapt>=1.11.0 (from tensorflow>=2.0.0)
  Downloading wrapt-1.17.3-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (6.4 kB)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow>=2.0.0)
  Downloading grpcio-1.74.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting tensorboard~=2.20.0 (from tensorflow>=2.0.0)
  Downloading tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Collecting keras>=3.10.0 (from tensorflow>=2.0.0)
  Downloading keras-3.11.3-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: numpy>=1.26.0 in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from tensorflow>=2.0.0) (2.2.6)
Collecting h5py>=3.11.0 (from tensorflow>=2.0.0)
  Downloading h5py-3.14.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.7 kB)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from tensorflow>=2.0.0) (0.5.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from requests<3,>=2.21.0->tensorflow>=2.0.0) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from requests<3,>=2.21.0->tensorflow>=2.0.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from requests<3,>=2.21.0->tensorflow>=2.0.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from requests<3,>=2.21.0->tensorflow>=2.0.0) (2025.8.3)
Collecting markdown>=2.6.8 (from tensorboard~=2.20.0->tensorflow>=2.0.0)
  Downloading markdown-3.8.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: pillow in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from tensorboard~=2.20.0->tensorflow>=2.0.0) (11.3.0)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard~=2.20.0->tensorflow>=2.0.0)
  Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard~=2.20.0->tensorflow>=2.0.0)
  Downloading werkzeug-3.1.3-py3-none-any.whl.metadata (3.7 kB)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow>=2.0.0)
  Downloading wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
Collecting rich (from keras>=3.10.0->tensorflow>=2.0.0)
  Downloading rich-14.1.0-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras>=3.10.0->tensorflow>=2.0.0)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.10.0->tensorflow>=2.0.0)
  Downloading optree-0.17.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (33 kB)
Requirement already satisfied: MarkupSafe>=2.1.1 in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow>=2.0.0) (3.0.2)
Collecting markdown-it-py>=2.2.0 (from rich->keras>=3.10.0->tensorflow>=2.0.0)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich->keras>=3.10.0->tensorflow>=2.0.0)
  Downloading pygments-2.19.2-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow>=2.0.0)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading tensorflow-2.20.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (620.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 620.8/620.8 MB 3.1 MB/s eta 0:00:00
Downloading grpcio-1.74.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 3.0 MB/s eta 0:00:00
Downloading tensorboard-2.20.0-py3-none-any.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 3.0 MB/s eta 0:00:00
Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 3.1 MB/s eta 0:00:00
Downloading absl_py-2.3.1-py3-none-any.whl (135 kB)
Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Downloading wheel-0.45.1-py3-none-any.whl (72 kB)
Downloading flatbuffers-25.2.10-py2.py3-none-any.whl (30 kB)
Downloading gast-0.6.0-py3-none-any.whl (21 kB)
Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
Downloading h5py-3.14.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 3.2 MB/s eta 0:00:00
Downloading keras-3.11.3-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 3.4 MB/s eta 0:00:00
Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 3.3 MB/s eta 0:00:00
Downloading markdown-3.8.2-py3-none-any.whl (106 kB)
Downloading opt_einsum-3.4.0-py3-none-any.whl (71 kB)
Downloading termcolor-3.1.0-py3-none-any.whl (7.7 kB)
Downloading werkzeug-3.1.3-py3-none-any.whl (224 kB)
Downloading wrapt-1.17.3-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (88 kB)
Downloading namex-0.1.0-py3-none-any.whl (5.9 kB)
Downloading optree-0.17.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (414 kB)
Downloading rich-14.1.0-py3-none-any.whl (243 kB)
Downloading pygments-2.19.2-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 3.4 MB/s eta 0:00:00
Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: namex, libclang, flatbuffers, wrapt, wheel, werkzeug, termcolor, tensorboard-data-server, pygments, optree, opt_einsum, mdurl, markdown, h5py, grpcio, google_pasta, gast, absl-py, tensorboard, markdown-it-py, astunparse, rich, keras, tensorflow

Successfully installed absl-py-2.3.1 astunparse-1.6.3 flatbuffers-25.2.10 gast-0.6.0 google_pasta-0.2.0 grpcio-1.74.0 h5py-3.14.0 keras-3.11.3 libclang-18.1.1 markdown-3.8.2 markdown-it-py-4.0.0 mdurl-0.1.2 namex-0.1.0 opt_einsum-3.4.0 optree-0.17.0 pygments-2.19.2 rich-14.1.0 tensorboard-2.20.0 tensorboard-data-server-0.7.2 tensorflow-2.20.0 termcolor-3.1.0 werkzeug-3.1.3 wheel-0.45.1 wrapt-1.17.3

requirements: AutoUpdate success ✅ 290.2s
WARNING ⚠ requirements: Restart runtime or rerun command for updates to take effect

requirements: Ultralytics requirements ['ai-edge-litert>=1.2.0,<1.4.0', 'onnxslim>=0.1.65', 'onnxruntime'] not found, attempting AutoUpdate...
ERROR: Could not find a version that satisfies the requirement ai-edge-litert<1.4.0,>=1.2.0 (from versions: none)
ERROR: No matching distribution found for ai-edge-litert<1.4.0,>=1.2.0
WARNING ⚠ Retry 1/2 failed: Command 'pip install --no-cache-dir "ai-edge-litert>=1.2.0,<1.4.0" "onnxslim>=0.1.65" "onnxruntime" --extra-index-url https://pypi.ngc.nvidia.com' returned non-zero exit status 1.
ERROR: Could not find a version that satisfies the requirement ai-edge-litert<1.4.0,>=1.2.0 (from versions: none)
ERROR: No matching distribution found for ai-edge-litert<1.4.0,>=1.2.0
WARNING ⚠ Retry 2/2 failed: Command 'pip install --no-cache-dir "ai-edge-litert>=1.2.0,<1.4.0" "onnxslim>=0.1.65" "onnxruntime" --extra-index-url https://pypi.ngc.nvidia.com' returned non-zero exit status 1.
WARNING ⚠ requirements: ❌ Command 'pip install --no-cache-dir "ai-edge-litert>=1.2.0,<1.4.0" "onnxslim>=0.1.65" "onnxruntime" --extra-index-url https://pypi.ngc.nvidia.com' returned non-zero exit status 1.

TensorFlow SavedModel: starting export with tensorflow 2.20.0...
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/calibration_image_sample_data_20x128x128x3_float32.npy.zip to 'calibration_image_sample_data_20xDownloading https://github.com/ultralytics/assets/releases/download/v8.3.0/calibration_image_sample_data_20x128x128x3_float32.npy.zip to 'calibration_image_sample_data_20xDownloading https://github.com/ultralytics/assets/releases/download/v8.3.0/calibration_image_sample_data_20x128x128x3_float32.npy.zip to 'calibration_image_sample_data_20xDownloading https://github.com/ultralytics/assets/releases/download/v8.3.0/calibration_image_sample_data_20x128x128x3_float32.npy.zip to 'calibration_image_sample_data_20xDownloading https://github.com/ultralytics/assets/releases/download/v8.3.0/calibration_image_sample_data_20x128x128x3_float32.npy.zip to 'calibration_image_sample_data_20x128x128x3_float32.npy.zip': 100% ━━━━━━━━━━━━ 1.1/1.1MB 2.7MB/s 0.4s
Unzipping calibration_image_sample_data_20x128x128x3_float32.npy.zip to /home/norman/ufo_ki/calibration_image_sample_data_20x128x128x3_float32.npy...: 100% ━━━━━━━━━━━━ 1/Unzipping calibration_image_sample_data_20x128x128x3_float32.npy.zip to /home/norman/ufo_ki/calibration_image_sample_data_20x128x128x3_float32.npy...: 100% ━━━━━━━━━━━━ 1/1 35.6files/s 0.0s
requirements: Ultralytics requirements ['onnxslim>=0.1.65', 'onnxruntime'] not found, attempting AutoUpdate...
Collecting onnxslim>=0.1.65
  Downloading onnxslim-0.1.65-py3-none-any.whl.metadata (7.6 kB)
Collecting onnxruntime
  Downloading onnxruntime-1.22.1-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: onnx in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from onnxslim>=0.1.65) (1.19.0)
Requirement already satisfied: sympy>=1.13.3 in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from onnxslim>=0.1.65) (1.14.0)
Requirement already satisfied: packaging in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from onnxslim>=0.1.65) (25.0)
Collecting colorama (from onnxslim>=0.1.65)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting coloredlogs (from onnxruntime)
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: flatbuffers in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from onnxruntime) (25.2.10)
Requirement already satisfied: numpy>=1.21.6 in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from onnxruntime) (2.2.6)
Requirement already satisfied: protobuf in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from onnxruntime) (6.32.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from sympy>=1.13.3->onnxslim>=0.1.65) (1.3.0)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime)
  Downloading humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: typing_extensions>=4.7.1 in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from onnx->onnxslim>=0.1.65) (4.15.0)
Requirement already satisfied: ml_dtypes in /home/norman/.yolov11_venv/lib/python3.13/site-packages (from onnx->onnxslim>=0.1.65) (0.5.3)
Downloading onnxslim-0.1.65-py3-none-any.whl (164 kB)
Downloading onnxruntime-1.22.1-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 2.7 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Downloading humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Installing collected packages: humanfriendly, colorama, coloredlogs, onnxslim, onnxruntime

Successfully installed colorama-0.4.6 coloredlogs-15.0.1 humanfriendly-10.0 onnxruntime-1.22.1 onnxslim-0.1.65

requirements: AutoUpdate success ✅ 9.0s
WARNING ⚠ requirements: Restart runtime or rerun command for updates to take effect


ONNX: starting export with onnx 1.19.0 opset 19...
ONNX: slimming with onnxslim 0.1.65...
ONNX: export success ✅ 10.3s, saved as 'runs/detect/train/weights/best.onnx' (10.2 MB)
ERROR ❌ TensorFlow SavedModel: export failure 308.8s: module 'tensorflow._api.v2.compat.v2.__internal__' has no attribute 'register_load_context_function'
Traceback (most recent call last):
  File "/home/norman/.yolov11_venv/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ~~~~~~~~~~^^
  File "/home/norman/.yolov11_venv/lib/python3.13/site-packages/ultralytics/cfg/__init__.py", line 986, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/norman/.yolov11_venv/lib/python3.13/site-packages/ultralytics/engine/model.py", line 734, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/norman/.yolov11_venv/lib/python3.13/site-packages/ultralytics/engine/exporter.py", line 497, in __call__
    f[5], keras_model = self.export_saved_model()
                        ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/norman/.yolov11_venv/lib/python3.13/site-packages/ultralytics/engine/exporter.py", line 199, in outer_func
    raise e
  File "/home/norman/.yolov11_venv/lib/python3.13/site-packages/ultralytics/engine/exporter.py", line 194, in outer_func
    f, model = inner_func(*args, **kwargs)
               ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/norman/.yolov11_venv/lib/python3.13/site-packages/ultralytics/engine/exporter.py", line 1006, in export_saved_model
    import onnx2tf  # scoped for after ONNX export for reduced conflict during import
    ^^^^^^^^^^^^^^
  File "/home/norman/.yolov11_venv/lib/python3.13/site-packages/onnx2tf/__init__.py", line 1, in <module>
    from onnx2tf.onnx2tf import convert, main
  File "/home/norman/.yolov11_venv/lib/python3.13/site-packages/onnx2tf/onnx2tf.py", line 29, in <module>
    import tf_keras
  File "/home/norman/.yolov11_venv/lib/python3.13/site-packages/tf_keras/__init__.py", line 3, in <module>
    from tf_keras import __internal__
  File "/home/norman/.yolov11_venv/lib/python3.13/site-packages/tf_keras/__internal__/__init__.py", line 3, in <module>
    from tf_keras.__internal__ import backend
  File "/home/norman/.yolov11_venv/lib/python3.13/site-packages/tf_keras/__internal__/backend/__init__.py", line 3, in <module>
    from tf_keras.src.backend import _initialize_variables as initialize_variables
  File "/home/norman/.yolov11_venv/lib/python3.13/site-packages/tf_keras/src/__init__.py", line 21, in <module>
    from tf_keras.src import applications
  File "/home/norman/.yolov11_venv/lib/python3.13/site-packages/tf_keras/src/applications/__init__.py", line 18, in <module>
    from tf_keras.src.applications.convnext import ConvNeXtBase
  File "/home/norman/.yolov11_venv/lib/python3.13/site-packages/tf_keras/src/applications/convnext.py", line 33, in <module>
    from tf_keras.src.engine import sequential
  File "/home/norman/.yolov11_venv/lib/python3.13/site-packages/tf_keras/src/engine/sequential.py", line 24, in <module>
    from tf_keras.src.engine import functional
  File "/home/norman/.yolov11_venv/lib/python3.13/site-packages/tf_keras/src/engine/functional.py", line 33, in <module>
    from tf_keras.src.engine import training as training_lib
  File "/home/norman/.yolov11_venv/lib/python3.13/site-packages/tf_keras/src/engine/training.py", line 48, in <module>
    from tf_keras.src.saving import saving_api
  File "/home/norman/.yolov11_venv/lib/python3.13/site-packages/tf_keras/src/saving/saving_api.py", line 25, in <module>
    from tf_keras.src.saving.legacy import save as legacy_sm_saving_lib
  File "/home/norman/.yolov11_venv/lib/python3.13/site-packages/tf_keras/src/saving/legacy/save.py", line 27, in <module>
    from tf_keras.src.saving.legacy.saved_model import load_context
  File "/home/norman/.yolov11_venv/lib/python3.13/site-packages/tf_keras/src/saving/legacy/saved_model/load_context.py", line 68, in <module>
    tf.__internal__.register_load_context_function(in_load_context)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'tensorflow._api.v2.compat.v2.__internal__' has no attribute 'register_load_context_function'. Did you mean: 'register_call_context_function'?
``` 

and then the program exits.

I ran it on Debian 13.

### Environment

absl-py==2.3.1
astunparse==1.6.3
certifi==2025.8.3
charset-normalizer==3.4.3
colorama==0.4.6
coloredlogs==15.0.1
contourpy==1.3.3
cycler==0.12.1
filelock==3.19.1
flatbuffers==25.2.10
fonttools==4.59.2
fsspec==2025.7.0
gast==0.6.0
google-pasta==0.2.0
grpcio==1.74.0
h5py==3.14.0
humanfriendly==10.0
idna==3.10
Jinja2==3.1.6
keras==3.11.3
kiwisolver==1.4.9
libclang==18.1.1
Markdown==3.8.2
markdown-it-py==4.0.0
MarkupSafe==3.0.2
matplotlib==3.10.5
mdurl==0.1.2
ml_dtypes==0.5.3
mpmath==1.3.0
namex==0.1.0
networkx==3.5
numpy==2.2.6
nvidia-cublas-cu12==12.8.4.1
nvidia-cuda-cupti-cu12==12.8.90
nvidia-cuda-nvrtc-cu12==12.8.93
nvidia-cuda-runtime-cu12==12.8.90
nvidia-cudnn-cu12==9.10.2.21
nvidia-cufft-cu12==11.3.3.83
nvidia-cufile-cu12==1.13.1.3
nvidia-curand-cu12==10.3.9.90
nvidia-cusolver-cu12==11.7.3.90
nvidia-cusparse-cu12==12.5.8.93
nvidia-cusparselt-cu12==0.7.1
nvidia-nccl-cu12==2.27.3
nvidia-nvjitlink-cu12==12.8.93
nvidia-nvtx-cu12==12.8.90
onnx==1.19.0
onnx2tf==1.28.2
onnx_graphsurgeon==0.5.8
onnxruntime==1.22.1
onnxslim==0.1.65
opencv-python==4.12.0.88
opt_einsum==3.4.0
optree==0.17.0
packaging==25.0
pillow==11.3.0
polars==1.32.3
protobuf==6.32.0
psutil==7.0.0
py-cpuinfo==9.0.0
Pygments==2.19.2
pyparsing==3.2.3
python-dateutil==2.9.0.post0
PyYAML==6.0.2
requests==2.32.5
rich==14.1.0
scipy==1.16.1
setuptools==80.9.0
six==1.17.0
sng4onnx==1.0.4
sympy==1.14.0
tensorboard==2.20.0
tensorboard-data-server==0.7.2
tensorflow==2.20.0
termcolor==3.1.0
tf-keras==2.15.0
torch==2.8.0
torchvision==0.23.0
triton==3.4.0
typing_extensions==4.15.0
ultralytics==8.3.189
ultralytics-thop==2.0.16
urllib3==2.5.0
Werkzeug==3.1.3
wheel==0.45.1
wrapt==1.17.3

### Minimal Reproducible Example

yolo task=detect mode=train data=dataset.yaml epochs=1000 imgsz=800 model=yolo11n.pt hsv_h=0.03 hsv_s=0.6 hsv_v=0.5 degrees=180 shear=30 perspective=0.0001 fliplr=1 mosaic=0.1 mixup=0.1 cutmix=0.1 copy_paste=0.1 batch=-1

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Y-T-G**
Python 3.13 causes issues like:
https://community.ultralytics.com/t/speed-up-inference-time-for-the-model-trained-with-yolo12x/1384/13?u=toxite

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://www.ultralytics.com/actions)</sub>

### 🌟 Summary
Adds a clear warning in the Quickstart docs that Python 3.13+ is experimental and recommends using Python 3.8–3.12 for reliable Ultralytics usage. ⚠️🐍

### 📊 Key Changes
- Introduces a "Python 3.13+ not fully supported" warning in docs/en/quickstart.md.
- Specifies supported Python versions: tested and verified on 3.8–3.12.
- Advises users that 3.13+ may work but is experimental and could cause unexpected issues.

### 🎯 Purpose & Impact
- Reduces installation and runtime surprises by setting clear version expectations. ✅
- Helps users choose stable environments (e.g., Python 3.12) for consistent performance. 🧩
- Minimizes support friction and troubleshooting related to Python 3.13 compatibility. 🛠️

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Y-T-G, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! This is an automated response to help speed things up—an Ultralytics engineer will review and assist soon. In the meantime, please review the checklist below to ensure a smooth merge, especially for your docs-focused update on Python 3.13+ support ⚠️🐍

- ✅ Define a Purpose: Clearly explain the purpose of your fix or feature in your PR description, and link to any relevant issues. Ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ Synchronize with Source: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ Ensure CI Checks Pass: Verify all Ultralytics Continuous Integration (CI) checks are passing. If any checks fail, please address the issues. See the CI guide for details.
- ✅ Update Documentation: Update the relevant documentation for any new or modified features. Since this PR adjusts Quickstart guidance, please confirm the version note is consistent across related install/setup pages.
- ✅ Add Tests: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ Sign the CLA: Please ensure you have signed our Contributor License Agreement if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ Minimize Changes: Limit your changes to the minimum necessary for your bug fix or feature addition. "It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is." — Bruce Lee

Quick tips for this PR:
- For docs-only changes, double-check the preview to ensure the warning renders correctly in Quickstart.
- If mentioning supported Python versions, ensure they align consistently with the current tested range referenced elsewhere in the docs.

For more guidance, please refer to our Contributing Guide. Don’t hesitate to leave a comment if you have any questions. Thank you for contributing to Ultralytics! 🚀

References:
- Relevant issues: https://github.com/ultralytics/ultralytics/issues
- CI guide: https://docs.ultralytics.com/help/CI/
- Documentation: https://docs.ultralytics.com/
- Contributor License Agreement (CLA): https://docs.ultralytics.com/help/CLA/
- Contributing Guide: https://docs.ultralytics.com/help/contributing/
