### ISSUE TITLE
export TensorRT fail

### ISSUE THREAD

**Issue by sandelush** [ultralytics/ultralytics#1600]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

PS C:\Users\devel\Desktop\mask> yolo export model=C:\Users\devel\Desktop\mask\runs\detect\train3\weights\best.pt format=engine device=0
Ultralytics YOLOv8.0.56  Python-3.9.13 torch-2.0.0+cu118 CUDA:0 (NVIDIA GeForce RTX 2060 SUPER, 8192MiB)
Model summary (fused): 168 layers, 3006233 parameters, 0 gradients, 8.1 GFLOPs

PyTorch: starting from C:\Users\devel\Desktop\mask\runs\detect\train3\weights\best.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 7, 8400) (5.9 MB)

ONNX: starting export with onnx 1.13.1...
============= Diagnostic Run torch.onnx.export version 2.0.0+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

ONNX: simplifying with onnxsim 0.4.19...
ONNX: export success  1.0s, saved as C:\Users\devel\Desktop\mask\runs\detect\train3\weights\best.onnx (0.1 MB)

TensorRT: starting export with TensorRT 8.6.0...
[03/24/2023-15:02:45] [TRT] [I] [MemUsageChange] Init CUDA: CPU +324, GPU +0, now: CPU 8418, GPU 2306 (MiB)
[03/24/2023-15:02:52] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1014, GPU +172, now: CPU 10595, GPU 2478 (MiB)
[03/24/2023-15:02:52] [TRT] [W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
[03/24/2023-15:02:52] [TRT] [I] ----------------------------------------------------------------
[03/24/2023-15:02:52] [TRT] [I] Input filename:   C:\Users\devel\Desktop\mask\runs\detect\train3\weights\best.onnx
[03/24/2023-15:02:52] [TRT] [I] ONNX IR version:  0.0.8
[03/24/2023-15:02:52] [TRT] [I] Opset version:    18
[03/24/2023-15:02:52] [TRT] [I] Producer name:    pytorch
[03/24/2023-15:02:52] [TRT] [I] Producer version: 2.0.0
[03/24/2023-15:02:52] [TRT] [I] Domain:
[03/24/2023-15:02:52] [TRT] [I] Model version:    0
[03/24/2023-15:02:52] [TRT] [I] Doc string:
[03/24/2023-15:02:52] [TRT] [I] ----------------------------------------------------------------
[03/24/2023-15:02:52] [TRT] [E] ModelImporter.cpp:768: While parsing node number 9 [Split -> "/model.2/Split_output_0"]:
[03/24/2023-15:02:52] [TRT] [E] ModelImporter.cpp:769: --- Begin node ---
[03/24/2023-15:02:52] [TRT] [E] ModelImporter.cpp:770: input: "/model.2/cv1/act/Mul_output_0"
input: "model.0.conv.bias"
output: "/model.2/Split_output_0"
output: "/model.2/Split_output_1"
name: "/model.2/Split"
op_type: "Split"
attribute {
  name: "axis"
  i: 1
  type: INT
}

[03/24/2023-15:02:52] [TRT] [E] ModelImporter.cpp:771: --- End node ---
[03/24/2023-15:02:52] [TRT] [E] ModelImporter.cpp:774: ERROR: builtin_op_importers.cpp:4686 In function importSplit:
[6] Assertion failed: (splitList.empty() || (splitList.size() == numOutputs)) && "The shape of the split attribute misaligns with the number of outputs."
TensorRT: export failure  8.7s: failed to load ONNX file: C:\Users\devel\Desktop\mask\runs\detect\train3\weights\best.onnx

### Environment

Ultralytics YOLOv8.0.56  Python-3.9.13 torch-2.0.0+cu118 CUDA:0 (NVIDIA GeForce RTX 2060 SUPER, 8192MiB)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@sandelush TensorRT export works correctly with torch 2.0:

<img width="1549" alt="Screenshot 2023-03-24 at 14 57 45" src="https://user-images.githubusercontent.com/26833433/227541116-1be54c71-e67d-45f8-a7fd-35e0d8b460bc.png">


We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by triple-Mu** [comment]
Maybe add `--simplify True` ?

**Comment by pderrenger** [comment]
@triple-Mu Good suggestion! Adding `--simplify True` to the export command may help simplify the ONNX model before attempting to export it to TensorRT. Give it a try and let us know if it resolves the issue. If the problem persists, please ensure to provide a minimum reproducible example following the guidelines in the previous message so we can further assist you. Thank you for your input! 🙌
