### PR TITLE
New Google LiteRT export replaces legacy TFLite and TF.js

### PR DESCRIPTION
**Pull request by ambitious-octopus**
This pull request adds support for exporting models to the `liteRT` format in the Ultralytics framework. The changes cover updates to export format definitions, the exporter logic, and the backend initialization to ensure `liteRT` is recognized and handled correctly.

### Exporter enhancements

* Added `liteRT` to the list of supported export formats in `export_formats()` within `ultralytics/engine/exporter.py`, including its arguments and capabilities.
* Updated the exporter logic to handle the `litert` flag, ensuring the format is recognized and processed during export.
* Implemented the `export_litert` method, which uses the `ai_edge_torch` library to convert and export models to the `liteRT` format, and saves associated metadata.
* Integrated the new export method into the exporter’s workflow, so that when the `litert` flag is set, the model is exported using the new method.

### Backend integration

* Updated the backend initialization in `ultralytics/nn/autobackend.py` to recognize the `litert` format, ensuring compatibility throughout the model loading and inference pipeline.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://www.ultralytics.com/actions)</sub>

**WARNING ⚠️** this PR is very large, summary may not cover all changes.

### 🌟 Summary
This PR introduces **LiteRT** as Ultralytics’ new unified `.tflite` export and inference path, replacing standalone **TFLite** and **TF.js** workflows across the codebase, docs, tests, and platform references 🚀

### 📊 Key Changes
- **Added a new `litert` export format** for YOLO models that outputs a single `.tflite` file for **mobile, edge, embedded, and browser** deployment.
- **Deprecated `tflite` and `tfjs` export formats**:
  - `format="tflite"` and `format="tfjs"` still work, but now show a warning and automatically export as `format="litert"`.
- **Added a new LiteRT inference backend**:
  - `.tflite` models now load through a dedicated `LiteRTBackend` in `AutoBackend`.
  - Includes support for both newer LiteRT exports and older legacy `.tflite` files.
- **Expanded quantization support** for LiteRT:
  - Added support for `w8a32` quantization.
  - Updated validation and export rules to reflect LiteRT-specific quantization behavior.
- **Updated export system and dependencies**:
  - New `export-litert` dependency group added in `pyproject.toml`.
  - Export format tables and logic now list **LiteRT** instead of separate TFLite/TF.js entries.
- **Added tests for LiteRT export** ✅
  - New test coverage checks LiteRT export across tasks and quantization modes.
  - Old TFLite-specific export tests were removed.
- **Large documentation refresh** 📚
  - Added a full new [LiteRT integration guide](../integrations/litert.md).
  - Marked **TFLite** and **TF.js** docs as deprecated.
  - Replaced many references across guides, model pages, platform docs, and FAQs from TFLite/TF.js to LiteRT.
- **Cleaned up old examples**
  - Removed the older `YOLOv8-TFLite-Python` example and related references.

### 🎯 Purpose & Impact
- **Simplifies deployment** 🌍  
  Users now have **one export target** for Android, iOS, edge devices, and browser use cases instead of juggling separate TFLite and TF.js paths.
- **Reduces confusion** 🧭  
  The docs, platform UI/docs, and export tables now reflect Google’s newer **LiteRT** naming and workflow more consistently.
- **Improves backward compatibility** 🔄  
  Existing users can still use `tflite` or `tfjs` commands for now, easing migration without breaking workflows immediately.
- **Strengthens on-device support** 📱  
  A dedicated LiteRT backend and updated quantization options make `.tflite` deployment more capable and better aligned with modern edge/browser runtimes.
- **Main impact is on export/deployment workflows, not model accuracy or training**  
  This PR is mostly about **deployment unification, documentation clarity, and runtime support**, so most users will mainly notice cleaner exports and updated terminology.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @ambitious-octopus, thank you for submitting a `ultralytics/ultralytics` 🚀 PR! This is an automated review helper, and a Ultralytics engineer will be with you shortly. In the meantime, please review the checklist below to help ensure a smooth merge:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). Ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: Update the relevant [documentation](https://docs.ultralytics.com/()) for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your bug fix or feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_ — Bruce Lee

For more guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing/). Don't hesitate to leave a comment if you have any questions. Thank you for contributing to Ultralytics! 🚀

File: ultralytics/engine/exporter.py [hunk 1]
```diff
@@ -796,6 +800,22 @@ def export_paddle(self, prefix=colorstr("PaddlePaddle:")):
...
         return f
+    
+    @try_export
+    def export_litert(self, prefix=colorstr("liteRT:")):
+        check_requirements("ai_edge_torch")
+        import ai_edge_torch
+        f = str(self.file.with_suffix(".tflite"))
+        
+        
+        sample_inputs = (torch.randn(1, 3, 640, 640),)
```
Comment (UltralyticsAssistant) [inline ultralytics/engine/exporter.py]: ⚠️ **HIGH**: `sample_inputs = (torch.randn(1, 3, 640, 640),)` forces a hard-coded 640×640 RGB tensor, which breaks LiteRT export for classification models, grayscale inputs, custom image sizes, or detection models trained with a different `imgsz`. Please build the sample input from the model’s actual input shape (e.g., reuse `self.args.imgsz`/`self.im` and channel count) so the export reflects the trained model.

**Suggested change:**
```suggestion
        sample_inputs = (torch.randn(1, self.model.model[-1].in_channels, *make_divisible(self.args.imgsz, self.stride)),)
```

File: ultralytics/engine/exporter.py [hunk 2]
```diff
@@ -796,6 +800,22 @@ def export_paddle(self, prefix=colorstr("PaddlePaddle:")):
...
+
+        edge_model = ai_edge_torch.convert(self.model, sample_inputs)
+        edge_model.export(f)
+        YAML.save("metadata.yaml", self.metadata)
```
Comment (UltralyticsAssistant) [inline ultralytics/engine/exporter.py]: 💡 **MEDIUM**: Saving `metadata.yaml` to the current working directory makes it easy to overwrite previous exports and separates metadata from the generated `.tflite` file. Consider writing it next to the exported model (`Path(f).with_name("metadata.yaml")`) to keep artifacts together and avoid collisions.

**Suggested change:**
```suggestion
        YAML.save(Path(f).with_name("metadata.yaml"), self.metadata)
```

**Review by UltralyticsAssistant — COMMENTED** [review]
## 🔍 PR Review

<sub>Made with ❤️ by [Ultralytics Actions](https://www.ultralytics.com/actions)</sub>

Address the LiteRT exporter’s fixed sample tensor so it matches each model’s actual input shape, and save `metadata.yaml` beside the generated `.tflite` to keep artifacts consistent and avoid overwrites.

💬 Posted 2 inline comments

**Review by ambitious-octopus — COMMENTED** [review]
@onuralpszr @lakshanthad testing with:

```python
from ultralytics import YOLO

# Load model
model = YOLO("yolo26n.pt")
del model.model.model[-1].one2one_cv2


def test_export_and_val(export_args, description):
    """Test export with given args and validate."""
    print(f"\n{'='*60}")
    print(f"Testing: {description}")
    print(f"Export args: {export_args}")
    print("=" * 60)

    # Export
    print("\nExporting...")
    
    exported_path = model.export(format="litert", imgsz=640, data="coco128.yaml", **export_args)
    print(f"Exported to: {exported_path}")

    # Validate
    print("\nValidating...")
    litert_model = YOLO(exported_path, task="detect")
    results = litert_model.val(data="coco128.yaml", imgsz=640)
    print(f"mAP50-95: {results.box.map:.4f}")
    return results.box.map


# Test cases
print("\n" + "=" * 60)
print("LiteRT Export Tests with Quantization")
print("=" * 60)

# Test 1: FP32 (default)
mAP_fp32 = test_export_and_val({}, "FP32 (default)")

# Test 2: FP16 (half)
mAP_fp16 = test_export_and_val({"half": True}, "FP16 (half precision)")

# Test 3: INT8
mAP_int8 = test_export_and_val({"int8": True}, "INT8 quantization")

# Summary
print("\n" + "=" * 60)
print("SUMMARY")
print("=" * 60)
print(f"FP32 mAP50-95: {mAP_fp32:.4f}")
print(f"FP16 mAP50-95: {mAP_fp16:.4f}")
print(f"INT8 mAP50-95: {mAP_int8:.4f}")
```

**Comment by Y-T-G** [comment]
Is it now called `litert-torch` instead of `ai-edge-torch`?

https://pypi.org/project/litert-torch/

**Comment by onuralpszr** [comment]
> Is it now called `litert-torch` instead of `ai-edge-torch`?
> 
> https://pypi.org/project/litert-torch/

Yes they changed the name I also notice talked to them I will update them as well. Thanks for heads up

**Comment by Y-T-G** [comment]
Seems like `litert-torch` also has a `torch` pin. `torch<2.10`

**Review by ambitious-octopus — COMMENTED** [review]
Hey @itsMarco-G, here is the PR.

**Comment by Y-T-G** [comment]
@onuralpszr I get this error using this branch

```
liteRT: starting export with ai_edge_torch...
ERROR ❌ liteRT: export failure 0.0s: module 'ai_edge_torch' has no attribute 'convert'
Traceback (most recent call last):
  File "/opt/conda/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/ultralytics/ultralytics/cfg/__init__.py", line 986, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ultralytics/ultralytics/engine/model.py", line 710, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ultralytics/ultralytics/engine/exporter.py", line 616, in __call__
    f[16] = self.export_litert()
            ^^^^^^^^^^^^^^^^^^^^
  File "/ultralytics/ultralytics/engine/exporter.py", line 255, in outer_func
    raise e
  File "/ultralytics/ultralytics/engine/exporter.py", line 247, in outer_func
    f = inner_func(*args, **kwargs)  # exported file/dir or tuple of (file/dir, *)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ultralytics/ultralytics/engine/exporter.py", line 866, in export_litert
    edge_model = ai_edge_torch.convert(self.model, sample_inputs)
                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'ai_edge_torch' has no attribute 'convert'
```

**Comment by onuralpszr** [comment]
> @onuralpszr I get this error using this branch
> 
> ```
> liteRT: starting export with ai_edge_torch...
> ERROR ❌ liteRT: export failure 0.0s: module 'ai_edge_torch' has no attribute 'convert'
> Traceback (most recent call last):
>   File "/opt/conda/bin/yolo", line 8, in <module>
>     sys.exit(entrypoint())
>              ^^^^^^^^^^^^
>   File "/ultralytics/ultralytics/cfg/__init__.py", line 986, in entrypoint
>     getattr(model, mode)(**overrides)  # default args from model
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ultralytics/ultralytics/engine/model.py", line 710, in export
>     return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ultralytics/ultralytics/engine/exporter.py", line 616, in __call__
>     f[16] = self.export_litert()
>             ^^^^^^^^^^^^^^^^^^^^
>   File "/ultralytics/ultralytics/engine/exporter.py", line 255, in outer_func
>     raise e
>   File "/ultralytics/ultralytics/engine/exporter.py", line 247, in outer_func
>     f = inner_func(*args, **kwargs)  # exported file/dir or tuple of (file/dir, *)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ultralytics/ultralytics/engine/exporter.py", line 866, in export_litert
>     edge_model = ai_edge_torch.convert(self.model, sample_inputs)
>                  ^^^^^^^^^^^^^^^^^^^^^
> AttributeError: module 'ai_edge_torch' has no attribute 'convert'
> ```


Let me push my new changes and re-test it. So you can re-test it.

**Comment by onuralpszr** [comment]
Todo list for litert

 torch pin problem needs to be solved it blocking or CI "Seems like litert-torch also has a torch pin. torch<2.10"
 
 This will block us to test in CI, I can prevent in CI test but when I user install our package and try to export it. LiteRT will lower the torch version will create in compatible torchvision package and causing error which you can see in our CI as well. 
 
 Other question is there any update about using stable package status because some of the packages are still nightly I can switch to stable but for example quantize package itself using tf-nightly
 
Question 2: Can we support macos or windows as well or just linux ? (Currently I cannot install in either of them last time I tested it) 

Question 3: For quantize package which config we should use for fp16 int8, I made  some selections but I am not sure a guide would be awesome. 

Thank you in advance

**Comment by Y-T-G** [comment]
It works for me. It also works with PyTorch 2.10 if you force install. Not sure why it is pinned to less than 2.10.

**Comment by Kanna-Sridhar** [comment]
[embedding_output.zip](https://github.com/user-attachments/files/26955549/embedding_output.zip)
Hi,
I used the Litert export format for the yolo26n model and I was able to extract the layer embedding for layer_0 with tensor shape [1,320,320,16] which is in the dropped file above. so how to verify these values are correct or to be more specific what do those values mean??

**Comment by glenn-jocher** [comment]
Those values are intermediate feature activations, not final detections: in LiteRT the tensor is usually `NHWC`, so your `[1,320,320,16]` matches PyTorch `[1,16,320,320]` from an early feature layer. The best verification is to run the exact same preprocessed input through the original PyTorch model, capture the matching layer output, transpose it to `NHWC`, and compare with a small tolerance; exact equality is not expected, especially for quantized exports. The [exporter reference](https://docs.ultralytics.com/reference/engine/exporter/) and [TFLite export guide](https://docs.ultralytics.com/integrations/tflite/) should help if you want to trace the exported tensors further.

**Comment by Kanna-Sridhar** [comment]
[test.py](https://github.com/user-attachments/files/27230201/test.py)
Hi,
The uploaded test file displays the MSE error rate between pytorch and litert outputs which is about 24.3393 and below is the snap of that so does this sound correct??
image
<

**Comment by glenn-jocher** [comment]
Not really—if this is intended to be a like-for-like layer comparison, `MSE=24.3393` usually points to a mismatch rather than a correct match, most often `NCHW` vs `NHWC`, different preprocessing, or comparing quantized values without dequantization; for `.tflite` outputs, compare the exact same input and layer after applying the tensor scale/zero-point, and the [TensorFlow export reference](https://docs.ultralytics.com/reference/utils/export/tensorflow/) is a useful hint here since the calibration path uses `BHWC` images.

**Comment by Kanna-Sridhar** [comment]
Hi,
i have attached images for  the pytorch and litert embedding for layer 0 since extracted file size is more than 25mb for the yolo26n model with code snippet so please whether the layer embeddings are correct
Screenshot 2026-05-05 120119
Screenshot 2026-05-05 120322
[test (1).py](https://github.com/user-attachments/files/27388763/test.1.py)

**Comment by glenn-jocher** [comment]
From screenshots alone I can’t reliably confirm the embeddings are correct; please paste the text output for the LiteRT tensor `shape`, `dtype`, and `quantization` parameters plus the exact PyTorch hook layer, because the check needs to be done on the same input after dequantizing LiteRT outputs and aligning `NCHW`/`NHWC`, and the [TensorFlow export reference](https://docs.ultralytics.com/reference/utils/export/tensorflow/) is the relevant guide here.

**Comment by Kanna-Sridhar** [comment]
but the file size are more than 25 MB and compressed to .tar format but i couldnt drop it here

**Comment by glenn-jocher** [comment]
No worries—you don’t need the full archive; please share a minimal repro instead with one test image, the exact PyTorch hook layer name, the text output of `interpreter.get_output_details()`, and a tiny tensor slice like `output[0, :4, :4, :4]` from both PyTorch and dequantized LiteRT, which is enough for us to verify whether the embeddings align.

**Comment by Kanna-Sridhar** [comment]
[pytorch slice and litert slice.txt](https://github.com/user-attachments/files/27465521/pytorch.slice.and.litert.slice.txt)
[test (1).py](https://github.com/user-attachments/files/27465523/test.1.py)
i have uploaded the tensor slice for pytorch and litert also the image used for this is bus.jpg and model used is yolo26n.pt so hence test(1).py file contains every details how these values were extracted because i feel like the values are close but not identical

**Comment by glenn-jocher** [comment]
Yes, that’s expected—LiteRT intermediate activations should be numerically close but not bit-identical to PyTorch, so the more reliable validation is to compare the final predictions on the same image after any dequantization; if the boxes, scores, and classes remain close, the exported layer output is behaving as expected.

**Comment by Kanna-Sridhar** [comment]
Thank you @glenn-jocher for the support

**Comment by glenn-jocher** [comment]
You’re welcome, glad it helped; if anything else comes up with the LiteRT export or output validation, feel free to post the details here.

**Comment by onuralpszr** [comment]
## ⚡ Actions Trigger

<sub>Made with ❤️ by [Ultralytics Actions](https://www.ultralytics.com/actions)</sub>

GitHub Actions below triggered via workflow dispatch for this PR at 2026-06-25 12:21:13 UTC with `@ultralytics/run-all` command
(available commands are `@ultralytics/run-all`, `@ultralytics/run-ci`, and `@ultralytics/run-docker`):

* ✅ [CI](https://github.com/ultralytics/ultralytics/actions/runs/28169625828): `ci.yml` run 24254
* ✅ [Publish Docker Images](https://github.com/ultralytics/ultralytics/actions/runs/28169627097): `docker.yml` run 2416

**Comment by onuralpszr** [comment]
## ⚡ Actions Trigger

<sub>Made with ❤️ by [Ultralytics Actions](https://www.ultralytics.com/actions)</sub>

GitHub Actions below triggered via workflow dispatch for this PR at 2026-06-25 12:51:45 UTC with `@ultralytics/run-all` command
(available commands are `@ultralytics/run-all`, `@ultralytics/run-ci`, and `@ultralytics/run-docker`):

* ✅ [CI](https://github.com/ultralytics/ultralytics/actions/runs/28171332173): `ci.yml` run 24267
* ✅ [Publish Docker Images](https://github.com/ultralytics/ultralytics/actions/runs/28171333435): `docker.yml` run 2417

**Comment by onuralpszr** [comment]
## ⚡ Actions Trigger

<sub>Made with ❤️ by [Ultralytics Actions](https://www.ultralytics.com/actions)</sub>

GitHub Actions below triggered via workflow dispatch for this PR at 2026-06-25 13:43:37 UTC with `@ultralytics/run-all` command
(available commands are `@ultralytics/run-all`, `@ultralytics/run-ci`, and `@ultralytics/run-docker`):

* ✅ [CI](https://github.com/ultralytics/ultralytics/actions/runs/28174512796): `ci.yml` run 24301
* ✅ [Publish Docker Images](https://github.com/ultralytics/ultralytics/actions/runs/28174514135): `docker.yml` run 2421

**Comment by Laughing-q** [comment]
@ambitious-octopus @onuralpszr Guys I found a couple of issue here:
- new litert does not support `nms` here like `tfite` does, running with `yolo export model=yolo11n.pt nms format=litert` and run inference with exported model it'd get incorrect results. Seeing this as a regression.
- new `LiteRTBackend` is not compatible with old exported as `tflite` weight:
  ```bash
  # export using main branch
  yolo export model=yolo26n.pt format=tflite
  # running on this branch
  yolo predict task=detect model=yolo26n_saved_model/yolo26n_float32.tflite imgsz=640
  ```
  would raise error, dimension mismatch, which I guess it's from the discrepancy of the input dimention between old tflite and litert, NCHW vs NHWC.
  Even if I temporarily update the code to bypass this dimension error it can run smoothly but the inference results are incorrect, I can tell the predict cls and conf scores are correct but bounding box coordinates are incorrect. I think this might be related to the discrepancy of normalize/denormalize output between tflite and litert. See the visual below:
bus

- Also introducing the new litert seems not eliminate the existence of onnx2tf package since we still need it for `pb` and `edgetpu`? 
  - https://github.com/ultralytics/ultralytics/blob/ab45ece7bbccbd7c03cc6a86dd82c612b75bf056/ultralytics/engine/exporter.py#L725-L729
  - https://github.com/ultralytics/ultralytics/blob/6c53a87e817310d0054d2129d388f5ca383e85fe/ultralytics/utils/export/tensorflow.py#L102-L115
  - which means we are not eliminating dependencies, but introducing new one?

**Comment by onuralpszr** [comment]
> * Also introducing the new litert seems not eliminate the existence of onnx2tf package since we still need it for `pb` and `edgetpu`?

Yes because of tensorflow I cannot remove it but litert bypass those deps and make export easier for tflite.

**Comment by onuralpszr** [comment]
> * new litert does not support `nms` here like `tfite` does, running with `yolo export model=yolo11n.pt nms format=litert` and run inference with exported model it'd get incorrect results. Seeing this as a regression.

I checked nms but new litert doesn't support torchvision.nms so I couldn't export this but I will check again

**Comment by onuralpszr** [comment]
> * would raise error, dimension mismatch, which I guess it's from the discrepancy of the input dimention between old tflite and litert, NCHW vs NHWC.
>   Even if I temporarily update the code to bypass this dimension error it can run smoothly but the inference results are incorrect, I can tell the predict cls and conf scores are correct but bounding box coordinates are incorrect. I think this might be related to the discrepancy of normalize/denormalize output between tflite and litert. See the visual below:

I will re-check and make sure okay with older style

**Comment by onuralpszr** [comment]
## ⚡ Actions Trigger

<sub>Made with ❤️ by [Ultralytics Actions](https://www.ultralytics.com/actions)</sub>

GitHub Actions below triggered via workflow dispatch for this PR at 2026-06-26 11:04:13 UTC with `@ultralytics/run-ci` command
(available commands are `@ultralytics/run-all`, `@ultralytics/run-ci`, and `@ultralytics/run-docker`):

* ✅ [CI](https://github.com/ultralytics/ultralytics/actions/runs/28233990989): `ci.yml` run 24379

**Comment by onuralpszr** [comment]
## ⚡ Actions Trigger

<sub>Made with ❤️ by [Ultralytics Actions](https://www.ultralytics.com/actions)</sub>

GitHub Actions below triggered via workflow dispatch for this PR at 2026-06-26 11:19:54 UTC with `@ultralytics/run-ci` command
(available commands are `@ultralytics/run-all`, `@ultralytics/run-ci`, and `@ultralytics/run-docker`):

* ✅ [CI](https://github.com/ultralytics/ultralytics/actions/runs/28234727820): `ci.yml` run 24381

**Comment by onuralpszr** [comment]
## ⚡ Actions Trigger

<sub>Made with ❤️ by [Ultralytics Actions](https://www.ultralytics.com/actions)</sub>

GitHub Actions below triggered via workflow dispatch for this PR at 2026-06-29 12:52:32 UTC with `@ultralytics/run-all` command
(available commands are `@ultralytics/run-all`, `@ultralytics/run-ci`, and `@ultralytics/run-docker`):

* ✅ [CI](https://github.com/ultralytics/ultralytics/actions/runs/28373325604): `ci.yml` run 24741
* ✅ [Publish Docker Images](https://github.com/ultralytics/ultralytics/actions/runs/28373326966): `docker.yml` run 2473

**Comment by onuralpszr** [comment]
## ⚡ Actions Trigger

<sub>Made with ❤️ by [Ultralytics Actions](https://www.ultralytics.com/actions)</sub>

GitHub Actions below triggered via workflow dispatch for this PR at 2026-06-29 15:54:03 UTC with `@ultralytics/run-all` command
(available commands are `@ultralytics/run-all`, `@ultralytics/run-ci`, and `@ultralytics/run-docker`):

* ✅ [CI](https://github.com/ultralytics/ultralytics/actions/runs/28384967295): `ci.yml` run 24774
* ✅ [Publish Docker Images](https://github.com/ultralytics/ultralytics/actions/runs/28384968698): `docker.yml` run 2478

**Review by glenn-jocher — APPROVED** [review]

**Comment by glenn-jocher** [comment]
## ⚡ Actions Trigger

<sub>Made with ❤️ by [Ultralytics Actions](https://www.ultralytics.com/actions)</sub>

GitHub Actions below triggered via workflow dispatch for this PR at 2026-06-29 20:50:33 UTC with `@ultralytics/run-all` command
(available commands are `@ultralytics/run-all`, `@ultralytics/run-ci`, and `@ultralytics/run-docker`):

* ✅ [CI](https://github.com/ultralytics/ultralytics/actions/runs/28401752401): `ci.yml` run 24848
* ✅ [Publish Docker Images](https://github.com/ultralytics/ultralytics/actions/runs/28401753384): `docker.yml` run 2484

**Review by onuralpszr — APPROVED** [review]

**Comment by glenn-jocher** [comment]
## ⚡ Actions Trigger

<sub>Made with ❤️ by [Ultralytics Actions](https://www.ultralytics.com/actions)</sub>

GitHub Actions below triggered via workflow dispatch for this PR at 2026-06-29 22:11:43 UTC with `@ultralytics/run-all` command
(available commands are `@ultralytics/run-all`, `@ultralytics/run-ci`, and `@ultralytics/run-docker`):

* ✅ [CI](https://github.com/ultralytics/ultralytics/actions/runs/28406019414): `ci.yml` run 24863
* ✅ [Publish Docker Images](https://github.com/ultralytics/ultralytics/actions/runs/28406020435): `docker.yml` run 2486

**Comment by UltralyticsAssistant** [comment]
🎉 Huge congratulations on merging this major LiteRT unification PR!

“As we look ahead into the next century, leaders will be those who empower others.” — Bill Gates

This update does exactly that: by bringing export, inference, docs, tests, and platform references together under **LiteRT**, it makes YOLO deployment simpler, clearer, and more accessible across mobile, edge, embedded, and browser workflows. The thoughtful backward compatibility and expanded quantization support make the impact even stronger.

Big thanks to @ambitious-octopus for driving this forward, with valuable contributions from @onuralpszr, @Y-T-G, @Kanna-Sridhar, @glenn-jocher, @lakshanthad, and @Laughing-q. This is a meaningful step toward a more unified and user-friendly Ultralytics experience 🚀
