### ISSUE TITLE
'WorldModel' object has no attribute 'clip_model'

### ISSUE THREAD

**Issue by beethogedeon** [ultralytics/ultralytics#9240]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> Cell In[4], line 2
>       1 # Define custom classes
> ----> 2 model.set_classes(["red box", "blue box", "green box","brown box"])
> 
> File /opt/conda/lib/python3.10/site-packages/ultralytics/models/yolo/model.py:96, in YOLOWorld.set_classes(self, classes)
>      89 def set_classes(self, classes):
>      90     """
>      91     Set classes.
>      92 
>      93     Args:
>      94         classes (List(str)): A list of categories i.e ["person"].
>      95     """
> ---> 96     self.model.set_classes(classes)
>      97     # Remove background if it's given
>      98     background = " "
> 
> File /opt/conda/lib/python3.10/site-packages/ultralytics/nn/tasks.py:575, in WorldModel.set_classes(self, text)
>     572     check_requirements("[git+https://github.com/openai/CLIP.git](git+https://github.com/openai/CLIP.git</span><span) style="color:rgb(175,0,0)">")
>     573     import clip
> --> 575 if not self.clip_model:
>     576     self.clip_model = clip.load("ViT-B/32")[0]
>     577 device = next(self.clip_model.parameters()).device
> 
> File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1695, in Module.__getattr__(self, name)
>    1693     if name in modules:
>    1694         return modules[name]
> -> 1695 raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
> 
> AttributeError: 'WorldModel' object has no attribute 'clip_model'

### Environment

Ultralytics YOLOv8.1.31 🚀 Python-3.10.13 torch-2.1.2 CUDA:0 (Tesla P100-PCIE-16GB, 16276MiB)
Setup complete ✅ (4 CPUs, 31.4 GB RAM, 5519.7/8062.4 GB disk)

### Minimal Reproducible Example

```python
!pip install ultralytics
```

```python
from ultralytics import YOLO
```
```python
# Initialize a YOLO-World model
model = YOLO('yolov8s-world.pt')
```
```python
# Define custom classes
model.set_classes(["red box", "blue box", "green box","brown box"])
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Burhan-Q** [comment]
@beethogedeon I can replicate this issue. You can use `pip install ultralytics=8.1.30` to roll back to the previous version where this should be working.

**Comment by beethogedeon** [comment]
> @beethogedeon I can replicate this issue. You can use `pip install ultralytics=8.1.30` to roll back to the previous version where this should be working.

Yeh!

**Comment by beethogedeon** [comment]
> @beethogedeon I can replicate this issue. You can use `pip install ultralytics=8.1.30` to roll back to the previous version where this should be working.

@Burhan-Q Yeh ! It's working on 8.1.30

**Comment by nadaakm** [comment]
i have the same thing with yoloworld :

**model = YOLOWorld(model_id="yolo_world/l")

###Using Non-Max Suppression (NMS) to Eliminate Double Detections
classes = ["bottle","soda can"]
model.set_classes(classes)

error:
AttributeError: 'WorldModel' object has no attribute 'clip_model'**

how can i fix that ?

**Comment by beethogedeon** [comment]
> i have the same thing with yoloworld :
> 
> **model = YOLOWorld(model_id="yolo_world/l")
> 
> ###Using Non-Max Suppression (NMS) to Eliminate Double Detections
> classes = ["bottle","soda can"]
> model.set_classes(classes)
> 
> error:
> AttributeError: 'WorldModel' object has no attribute 'clip_model'**
> 
> how can i fix that ?

@nadaakm Use `pip install ultralytics==8.1.30`

**Comment by nadaakm** [comment]
@beethogedeon thnx ! it works

**Comment by glenn-jocher** [comment]
@beethogedeon @nadaakm thanks for the bug report guys, we can reproduce and are creating a fix based on updating the attribute check:
```python
        if not getattr(self, "clip_model"):  # for backwards compatibility of models lacking clip_model attribute
```

**Comment by pkm-flick-it** [comment]
it started again even in ultralytics=8.1.30

ModuleNotFoundError: No module named 'clip.model'

everything was working yesterday, what happened today.

**Comment by Burhan-Q** [comment]
@pkm-flick-it the most recent version is `ultralytics==8.2.28` and the version you're using is from March 20, 2024. There was an issue that was addressed around then too, see https://github.com/ultralytics/ultralytics/pull/9253 (referenced just above your comment too). Definitely be sure to check out the CI tests as well, as there are integration tests that will show if there is an issue with the library (prevents anyone from merging breaking changes). <a href="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml?query=branch%3Amain"><img src="https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml/badge.svg" alt="Ultralytics CI"></a>

**Comment by pkm-flick-it** [comment]
@Burhan-Q  I am facing this issue despite of upgrading my ultralytics==8.2.28

Pleasse, if possible explain me in simple words

<This is coming to my command line>
WARNING ⚠️ yolov8s.pt appears to require 'clip.model', which is not in ultralytics requirements.
AutoInstall will run now for 'clip.model' but this feature will be removed in the future.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'
Traceback (most recent call last):
  File "C:\Users\p12m9\Documents\BioMechanics\evn\Lib\site-packages\ultralytics\nn\tasks.py", line 732, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p12m9\Documents\BioMechanics\evn\Lib\site-packages\torch\serialization.py", line 1025, in load
    return _load(opened_zipfile,
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p12m9\Documents\BioMechanics\evn\Lib\site-packages\torch\serialization.py", line 1446, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "C:\Users\p12m9\Documents\BioMechanics\evn\Lib\site-packages\torch\serialization.py", line 1439, in find_class
    return super().find_class(mod_name, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'clip.model'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\p12m9\Documents\BioMechanics\flick (Threading)\cv\main.py", line 6, in <module>
    from model_utlity import process_video
  File "c:\Users\p12m9\Documents\BioMechanics\flick (Threading)\cv\model_utlity.py", line 11, in <module>
    model = YOLO(MODEL_PATH)
            ^^^^^^^^^^^^^^^^
  File "C:\Users\p12m9\Documents\BioMechanics\evn\Lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\Users\p12m9\Documents\BioMechanics\evn\Lib\site-packages\ultralytics\engine\model.py", line 152, in __init__
    self._load(model, task=task)
  File "C:\Users\p12m9\Documents\BioMechanics\evn\Lib\site-packages\ultralytics\engine\model.py", line 241, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p12m9\Documents\BioMechanics\evn\Lib\site-packages\ultralytics\nn\tasks.py", line 806, in attempt_load_one_weight       
    ckpt, weight = torch_safe_load(weight)  # load ckpt
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p12m9\Documents\BioMechanics\evn\Lib\site-packages\ultralytics\nn\tasks.py", line 752, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p12m9\Documents\BioMechanics\evn\Lib\site-packages\torch\serialization.py", line 1025, in load
    return _load(opened_zipfile,
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p12m9\Documents\BioMechanics\evn\Lib\site-packages\torch\serialization.py", line 1446, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "C:\Users\p12m9\Documents\BioMechanics\evn\Lib\site-packages\torch\serialization.py", line 1439, in find_class
    return super().find_class(mod_name, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'clip.model'

**Comment by mschweig** [comment]
Hello @Burhan-Q , I am also facing the same issue with ultralytics==8.2.28.

**Comment by Burhan-Q** [comment]
@mschweig and @pkm-flick-it try deleting or moving your existing weights files, then load using `yolov8s-world.pt` or `yolov8s-worldv2.pt` so that it downloads a new copy of the default weights.

**Comment by mschweig** [comment]
Hi @Burhan-Q I am just loading the yolov8s-world.pt via 

`from ultralytics import YOLO

# Load model
model = YOLO("yolov8s-world.pt")

model.set_classes(["person"])`

Loading the model works but set_classes throw the clip error: AttributeError: module 'clip' has no attribute 'load'

**Comment by Burhan-Q** [comment]
@mschweig same here and I'm not getting any errors. 

```py
from ultralytics import YOLO, checks

checks()
>>> Ultralytics YOLOv8.2.31 🚀 Python-3.10.9 torch-2.1.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3080, 12288MiB)
>>> Setup complete ✅ (12 CPUs, 31.9 GB RAM, 751.3/1863.0 GB disk)

model = YOLO("yolov8s-world.pt")

>>> Downloading https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8s-world.pt to 'yolov8s-world.pt'...
100%|███████████████████████████████████████████████████████████████████████████████████████████| 25.9M/25.9M [00:00<00:00, 80.1MB/s]

_ = model.set_classes(["hotdog", "waffles", "fried chicken", ""])
result = model.predict()

>>> WARNING ⚠️ 'source' is missing. Using 'source=ultralytics/assets'.

>>> image 1/2 ultralytics/assets/bus.jpg: 640x480 (no detections), 141.0ms
>>> image 2/2 ultralytics/assets/zidane.jpg: 384x640 (no detections), 138.0ms
>>> Speed: 2.5ms preprocess, 139.5ms inference, 14.0ms postprocess per image at shape (1, 3, 384, 640)
```

**Comment by Dronakurl** [comment]
I see the same problem

```python
    def set_classes(self, text, batch=80, cache_clip_model=True):
        """Set classes in advance so that model could do offline-inference without clip model."""
        try:
            import clip
        except ImportError:
            check_requirements("git+https://github.com/ultralytics/CLIP.git")
            import clip

        if (
            not getattr(self, "clip_model", None) and cache_clip_model
        ):  # for backwards compatibility of models lacking clip_model attribute
>           self.clip_model = clip.load("ViT-B/32")[0]
E           AttributeError: module 'clip' has no attribute 'load'

/opt/venv/lib/python3.12/site-packages/ultralytics/nn/tasks.py:613: AttributeError
```

**Comment by pderrenger** [comment]
@Dronakurl thanks for reporting this issue. It appears there's a problem with the `clip` module. Please ensure you have the latest version of the Ultralytics package installed. If the issue persists, try deleting your existing weights and re-downloading them. This should resolve any compatibility issues. If you continue to face problems, please let us know.

**Comment by Dronakurl** [comment]
Deleting the weights did not work. This worked for me in the end.  
```bash
pip install "git+https://github.com/openai/CLIP.git"
```
The problem was only inside a docker container (with the same python version and requirements).

**Comment by pderrenger** [comment]
Thank you for sharing your solution. It's good to know that installing CLIP directly from the GitHub repository resolved the issue within your Docker container. If you encounter any further problems, please ensure you are using the latest version of the Ultralytics package. If the issue persists, feel free to reach out here.
