### ISSUE TITLE
object counting dont have attribute start_counting

### ISSUE THREAD

**Issue by codin-son** [ultralytics/ultralytics#16730]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hye! i had an issue when  i try to run example for object counting, i got error 

im0 = counter.start_counting(im0, tracks)
AttributeError: 'ObjectCounter' object has no attribute 'start_counting'

im running ultralytics version 8.3.5

Ultralytics 8.3.5 🚀 Python-3.8.10 torch-2.4.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060, 11931MiB)

should i use counting function only?

**Comment by UltralyticsAssistant** [comment]
👋 Hello @codin-son, thank you for reaching out to us at Ultralytics 🚀!

We recommend checking the latest [Ultralytics Docs](https://docs.ultralytics.com) for solutions and examples, which might be helpful in addressing your issue. 

To help us debug, providing a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) would be greatly appreciated. This ensures our team can assist you more effectively.

Since you're encountering an AttributeError, please ensure your `ultralytics` package is up to date with all the necessary [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml). You can update using:

```bash
pip install -U ultralytics
```

Make sure you're working in a [**Python>=3.8**](https://www.python.org/) environment with [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/).

For real-time conversations and community support, join us on [Discord](https://ultralytics.com/discord) 🎧. You might also find more in-depth discussions on [Discourse](https://community.ultralytics.com) or connect with peers on our [Subreddit](https://reddit.com/r/ultralytics).

Here's some more context about various environments:
- **Notebooks**: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Cloud Environments**: [Google Cloud](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/), [AWS](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/), [Docker](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/).

This is an automated response, but an Ultralytics engineer will be with you soon to provide further assistance. If any additional information becomes available, please feel free to update the issue. 😊

Stay tuned and happy coding!

**Comment by Y-T-G** [comment]
`start_counting` has been renamed to just `count`

Check the docs for updated code.

https://docs.ultralytics.com/guides/object-counting/

**Comment by RizwanMunawar** [comment]
@codin-son Hi, as @Y-T-G mentioned, we’ve made some changes, and `start_counting` has been renamed to `count`. Below is the updated code sample:

```python
import cv2
from ultralytics import solutions

cap = cv2.VideoCapture("path/to/video/file.mp4")
assert cap.isOpened(), "Error reading video file"
w, h, fps = (int(cap.get(prop)) for prop in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

# Define region points
region_points = [(20, 400), (1080, 404), (1080, 360), (20, 360)]

# Video writer
video_writer = cv2.VideoWriter("object_counting_output.avi", cv2.VideoWriter_fourcc(*"mp4v"), fps, (w, h))

# Initialize Object Counter
counter = solutions.ObjectCounter(
    show=True,
    region=region_points,
    model="yolo11n.pt",
)

# Process the video
while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("No more frames to process or video completed successfully.")
        break
    im0 = counter.count(im0)
    video_writer.write(im0)

cap.release()
video_writer.release()
cv2.destroyAllWindows()
```

I’m closing this issue for now. If you notice anything not working, feel free to open a new issue!

Thank you and best regards,  
The Ultralytics Team

**Comment by aforti1** [comment]
now .count() doesnt work anymore. not sure what it was updated to and how I can restore this version again.

**Comment by Y-T-G** [comment]
You can check the docs:

https://docs.ultralytics.com/guides/object-counting/#python

**Comment by codin-son** [comment]
thank you all. mad respect for all of you @Y-T-G @RizwanMunawar
