### ISSUE TITLE
Convert yolov8 model to tensorflow model (.pb)

### ISSUE THREAD

**Issue by aubinkg** [ultralytics/ultralytics#5365]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I try ton convert best.pt to sages-modem.pb 
I have this issue
How can i résolve it ?

### Additional

oserror: savedmodel file does not exist at: g:\yolov8s\best_saved_model\{saved_model.pbtxt|saved_model.pb}

**Comment by glenn-jocher** [comment]
@aubinkg hello,

Thank you for reaching out. Your issue seems to be related to model conversion from PyTorch to TensorFlow. In Ultralytics repository, you may use ONNX to intermediately convert the PyTorch model into a format that TensorFlow can read and then to a TensorFlow ".pb" file.

However, based on your issue, it seems the specified path doesn't contain a valid SavedModel format file. Please ensure you have correctly written your path and that the file you are trying to convert exists in that location.

It's also essential to ensure that the PyTorch model being converted was properly saved. If these things all check out and the problem persists, there might be an issue with compatibility or the translation process from PyTorch to TensorFlow.

Without additional information, it's difficult to identify the exact cause of your problem. I recommend providing the steps and the code you used for the conversion to better assist you. Remember to include any error messages that appear during this process. 

Thank you and I hope this helps. If you have further issues or questions, feel free to ask.

**Comment by aubinkg** [comment]
Thank for your message

from ultralytics import YOLO

# Load a model
#model = YOLO('yolov8n.pt')  # load an official model
model = YOLO(
'G:/yolov8/yolov8_face_detection.v1i.yolov8/supect_mouvement.v1i.yolov8/runs/detect/train/weights/
best.pt')  # load a custom trained model

# Export the model
model.export(format='saved_model')

Ingenieur travaux ( Maintenance industrielle - Informatique - Graphiste)
Professeur de Maths
Tel: 697 55 88 17




Le sam. 14 oct. 2023 à 03:48, Glenn Jocher ***@***.***> a
écrit :

**Comment by aubinkg** [comment]
Ingenieur travaux ( Maintenance industrielle - Informatique - Graphiste)
Professeur de Maths
Tel: 697 55 88 17

**Comment by glenn-jocher** [comment]
@aubinkg hello,

Thanks for providing a clearer picture of your issue. From the code you've shared, it seems like you're attempting to export your custom trained model. Unfortunately, the `model.export()` function requires a format to be specified, and `saved_model` may not be the correct format for the conversion process.

However, I noticed that you're loading the PyTorch model using a file path. Please ensure that this file path points directly to the .pt file of the trained model, and that the file exists in that location. Furthermore, the PyTorch model should be saved properly before you load it.

If all of this is correct but you're still experiencing an issue, it might be related to the compatibility of the models or some part of the process of translating between PyTorch and TensorFlow. Unfortunately, without more information about what happens when you try to run your code, it's very difficult to identify the actual cause of your problem.

Hope this helps. Should you have further issues or questions, remember to include any error messages you might get, as they greatly help in diagnosing the problem.

**Comment by aubinkg** [comment]
i can convert my best.pt model to best.onnx
there is no problem
but i want to convert it to .pb
i have these issues

yolo export model=best.pt format= onnx

Ingenieur travaux ( Maintenance industrielle - Informatique - Graphiste)
Professeur de Maths
Tel: 697 55 88 17




Le sam. 14 oct. 2023 à 12:07, Glenn Jocher ***@***.***> a
écrit :

**Comment by aubinkg** [comment]
i use TF2
Ingenieur travaux ( Maintenance industrielle - Informatique - Graphiste)
Professeur de Maths
Tel: 697 55 88 17




Le sam. 14 oct. 2023 à 12:07, Glenn Jocher ***@***.***> a
écrit :

**Comment by aubinkg** [comment]
i explain clearly my problem
i used yolov8 model to train a dataset and the end i generated best.pt
model  inside weights files
so i want to convert this custom in tensorflow2

 i used this code
from ultralytics import YOLO
<https://docs.ultralytics.com/modes/export/#__codelineno-0-2>
<https://docs.ultralytics.com/modes/export/#__codelineno-0-3># Load a model
<https://docs.ultralytics.com/modes/export/#__codelineno-0-4>model = YOLO('
yolov8n.pt') # load an official model
<https://docs.ultralytics.com/modes/export/#__codelineno-0-5>model = YOLO(
'path/to/best.pt') # load a custom trained model
<https://docs.ultralytics.com/modes/export/#__codelineno-0-6>
<https://docs.ultralytics.com/modes/export/#__codelineno-0-7># Export the
model <https://docs.ultralytics.com/modes/export/#__codelineno-0-8>model.
export(format='onnx')

is it possible to convert the .pt model to .pb model??

Ingenieur travaux ( Maintenance industrielle - Informatique - Graphiste)
Professeur de Maths
Tel: 697 55 88 17




Le sam. 14 oct. 2023 à 12:07, Glenn Jocher ***@***.***> a
écrit :

**Comment by glenn-jocher** [comment]
Hello @aubinkg,

Thanks for explaining your issue in further detail. In the context of YOLOv8, you can export your trained .pt model to ONNX format using the provided `export` function. However, exporting directly to TensorFlow's .pb format might not be directly supported.

In order to convert your trained model to .pb format, I would suggest doing it in two steps. First, use the `export` function to change the model to the ONNX format, and then use some converter tool like ONNX-Tensorflow or Tensorflow's ONNX import capabilities, to transform your model to .pb format.

Remember to check the compatibility of your model and the versions of PyTorch, ONNX and TensorFlow you're using, as this can cause errors in the conversion process. 

I hope this helps, and don't hesitate to ask if you have any further issues or questions!

**Comment by aubinkg** [comment]
hi,
i converted to onnx after to .pb file
But i have this issue
saved_model file has a .pb model
Ingenieur travaux ( Maintenance industrielle - Informatique - Graphiste)
Professeur de Maths
Tel: 697 55 88 17




Le dim. 15 oct. 2023 à 01:37, Glenn Jocher ***@***.***> a
écrit :

**Comment by aubinkg** [comment]
elemets inside saved_model file after conversion
Ingenieur travaux ( Maintenance industrielle - Informatique - Graphiste)
Professeur de Maths
Tel: 697 55 88 17




Le dim. 15 oct. 2023 à 01:37, Glenn Jocher ***@***.***> a
écrit :

**Comment by aubinkg** [comment]
i love yomov8
it is very fast
Ingenieur travaux ( Maintenance industrielle - Informatique - Graphiste)
Professeur de Maths
Tel: 697 55 88 17




Le dim. 15 oct. 2023 à 01:37, Glenn Jocher ***@***.***> a
écrit :

**Comment by glenn-jocher** [comment]
Hello @aubinkg,

Glad to hear that you're enjoying using YOLOv8. Yes, it's designed to provide fast, accurate object detection. If you encounter any issues or have any questions regarding the usage or implementation, feel free to ask. We're here to help. 

Regarding your previous question about converting a .pt model to a .pb format for TensorFlow: as already stated, you have to first convert your PyTorch model (.pt file) into ONNX format using the 'export' function. Once you have the ONNX model, you can then use a converter tool to finally convert your model into a .pb format that TensorFlow can use.
Keep in mind to check version compatibility of the different platforms to avoid errors during the conversion process.

Stay connected and happy coding!

**Comment by hartmannr76** [comment]
I'll actually add on to this - I'm using the CLI to export and was hitting the same error but the actual error seems a bit deeper. The file didn't exist because:

```
TypeError: Descriptors cannot not be created directly
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower)
```

Following some other threads elsewhere, I tried uninstalling and downgrading `pip uninstall protobuf && pip install protobuf==3.19` but then I get this error:

```
ImportError: cannot import name 'builder' from 'google.protobuf.internal'
```

So it seems like a mismatch of versions for this export process. Let me know if you'd like other details to help diagnose

**Comment by hartmannr76** [comment]
Actually, I just managed to get it to work with protobuf 3.20.3 - hope that helps!

**Comment by glenn-jocher** [comment]
@hartmannr76 hello,

Great to hear that you've managed to solve the issue with protobuf version 3.20.3!

Your experience indeed demonstrates that version mismatches can cause various issues, including the inability to export models properly. Often, downgrading or upgrading to a compatible version solves the problem, just like in your case.

To anyone else encountering similar issues, always ensure the compatibility of your libraries and packages, not only with your project but also with each other. It's really important in maintaining a stable and functioning environment.

Thank you for sharing your solution with the community. It can be a great help to others who might encounter the same or similar issue.

Feel free to reach out if you have any other questions or run into any more issues. Happy coding!
